Feature translation create root
reactjs/ko.react.dev pull request #1008
Opened 2024-07-19 04:03 UTC by icefoxand

## Message

Reference - Client API의 createRoot 의 번역을 완료하여 PR 합니다.
잘못된 부분이 있다면 꼭 알려주세요. 감사합니다!

![image](https://github.com/user-attachments/assets/87df9396-6ee2-4cef-8a19-8744ce28bf50)

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-07-24 08:33 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  * <CanaryBadge title="This feature is only available in the Canary channel" /> **optional** `onCaughtError`: Error Boundary에서 React가 에러를 잡았을 때 호출되는 콜백입니다. `componentStack`을 포함한 `errorInfo` 객체 및 Err
1. 'catch' 및 'caught'는 '잡았을 때' 와 '포착된' 으로 번역되기 보다는 '발견하였을 때'와 '발견된' 으로 번역하는 것이 좀 더 자연스러운 것 같습니다.
2. 영어 원문에서는 문장 순서가 and를 기준으로 '`error` caught by the ...' 다음에 '`errorInfo` object ...' 인데, 번역에서는 문장의 순서가 서로 뒤바뀌어 있습니다. 이 부분을 영어 원문 순서대로 바꿔주시면 좋을 것 같습니다.

2024-07-24 08:41 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  * **optional**  `onRecoverableError`: React가 에러로부터 자동으로 복구될 때 호출되는 콜백입니다.
1. 현재 페이지에서 'error'는 '오류'로 번역되는게 이전 번역과의 통일성이 있습니다. (기존 페이지에서 '에러'라는 용어는 사용되지 않았습니다.) 따라서, '에러'로 번역하신 부분들은 모두 '오류'로 수정해 주시는게 일관성이 있을 것 같습니다.

2024-07-24 08:42 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  * <CanaryBadge title="This feature is only available in the Canary channel" /> **optional** `onUncaughtError`: Error Boundary에서 잡히지 않은 에러가 발생했을 때 호출되는 콜백입니다. `componentStack`을 포함한 `errorInfo` 객체 및
47번 라인과 마찬가지로,

1. '잡히지 않은' -> '발견되지 않은'
2. and를 기준으로 번역본에서는 문장의 순서가 뒤바뀌어 있는데, 이 부분 영어 원문 순서대로

위 2개 수정해주시면 좋을 것 같습니다!

2024-07-24 08:57 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +앱이 온전히 React만으로 작성된 경우 전체 앱에 대해 단일 루트를 생성하세요.
현재 페이지에서는 '경우' 뒤에 `,`(콤마)가 붙어 있는 경우가 대다수 입니다. 일관성을 위해 콤마는 유지하는 편이 좋을 것 같습니다.

2024-07-24 09:08 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +페이지가 [React로만 작성되지 않은 경우](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page), React가 관리하는 각 최상위 UI에 대한 루트를 생성하기 위해 `createRoot`를 여러 번 호출할 수 있습니다. 루트마다 [`root.render
바로 위 같은 레벨의 헤딩(제목)이 '온전히 React***만으로***...' 로 시작하기 때문에, 일관성을 위해 이 부분은 수정하지 않는게 좋을 것 같습니다.

2024-07-24 09:18 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +같은 루트에서 `render`를 두 번 이상 호출할 수도 있습니다. 컴포넌트의 트리 구조가 이전 렌더링과 일치하는 한 React는 [기존 state를 유지](/learn/preserving-and-resetting-state)합니다. 다음 예제에서 input에 어떻게 타이핑하는지와 무관하게, 매초 반복되는 `render` 호출로 인한 업데이트가 아무런 문
'타이핑하는지와' -> '타이핑하는지와는' 으로 수정하면 좀 더 좋을 것 같습니다.

2024-07-24 09:22 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +### 처리되지 않은 에러에 대한 대화상자 표시하기 {/*show-a-dialog-for-uncaught-errors*/}
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:29 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> -You can use the `onUncaughtError` root option to display error dialogs:
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:30 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +`onUncaughtError` 루트 옵션을 사용해 에러 대화상자를 표시할 수 있습니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:31 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  기본 HTML의 에러 대화상자를 사용하였습니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:31 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  // 에러 메시지와 본문을 표시합니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:33 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +### Error Boundary 에러 표시하기 {/*displaying-error-boundary-errors*/}
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:43 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +`onCaughtError`는 최신 React Canary 릴리스에서만 사용할 수 있습니다.
-  is only available in the latest React Canary release.
- `onUncaughtError`는 오직 최신 버전의 React Canary 릴리스에서만 사용할 수 있습니다.

동일한 내용인데, 위에서의 번역 내용과 서로 다르게 번역되어 있습니다! 일관성 있게 수정 부탁드립니다.

2024-07-24 09:52 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +기본적으로 React는 Error Boundary에 의해 잡힌 모든 에러를 `console.error`에 기록합니다. 이 동작을 변경하려면 [Error Boundary](/reference/react/Component#catching-rendering-errors-with-an-error-boundary)에서 포착된 오류를 처리하기 위해 선택적인 `onC
1. '잡힌' 및 '포착된'은 '발견된'으로 수정 부탁드립니다.
2. '에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:53 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +<CodeStep step={1}>onCaughtError</CodeStep> 옵션은 두개의 인수를 받는 함수입니다.
용어 통일성을 위해 '인수'는 '인자'로 변경 부탁드립니다.

2024-07-24 09:53 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +1. Error Boundary에 의해 포착된 <CodeStep step={2}>error</CodeStep>.
'포착된'은 '발견된'으로 수정 부탁드립니다.

2024-07-24 09:54 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +2. 그 에러의 <CodeStep step={4}>componentStack</CodeStep>을 포함하는 <CodeStep step={3}>errorInfo</CodeStep>.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:54 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +`onCaughtError` 루트 옵션을 사용해 에러 대화상자를 표시하거나 로그에 기록된 에러 중 알고있는 것을 필터링 할 수 있습니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:55 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  // 제목을 설정 합니다.
'설정합니다' 로 붙여 써주세요!

2024-07-24 09:55 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  // 에러 메시지와 본문을 표시합니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 09:59 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  // 가능하면 원인을 표시합니다.
동일한 영어 원문에 대한 번역 내용이 서로 다릅니다.

위쪽에서는 '가능하다면 원인을 표시합니다.' 였습니다. 일관성 있게 수정 부탁드립니다.

2024-07-24 09:59 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +### 복구 가능한 에러에 대한 대화상자 표시하기 {/*displaying-a-dialog-for-recoverable-errors*/}
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 10:01 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +React는 렌더링 중 발생한 에러를 복구하기 위해 컴포넌트를 자동으로 두번 렌더링할 수 있습니다. 성공적으로 복구되면 React는 콘솔에 복구 가능한 에러를 로그로 남겨 개발자에게 알립니다. 이 동작을 override 하려면 선택적인 `onRecoverableError` 루트 옵션을 제공할 수 있습니다.
위쪽 문단에서 override는 '변경'으로 번역되었습니다. 'override 하려면' 은 '변경하려면'으로 번역 부탁드립니다.

2024-07-24 10:02 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +1. React가 발생시킨 <CodeStep step={2}>error</CodeStep>. 일부 에러는 기존 원인을 <CodeStep step={3}>error.cause</CodeStep>에 포함하기도 합니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 10:02 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +2. 에러의 <CodeStep step={5}>componentStack</CodeStep>을 포함하는 <CodeStep step={4}>errorInfo</CodeStep> 객체.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 10:02 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +에러 대화상자를 표시하기 위해 `onRecoverableError` 루트 옵션을 사용할 수 있습니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 10:02 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  // 에러 메시지와 본문을 표시합니다.
'에러'는 '오류'로 수정 부탁드립니다.

2024-07-24 10:03 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  // 가능하면 원인을 표시합니다.
위쪽에서는 '가능하다면 원인을 표시합니다.'로 번역되었습니다. 일관성을 맞춰주세요!

2024-07-24 10:03 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +  // 닫을 수 있는 경우 닫기 버튼을 표시합니다.
위쪽에서는 '닫을 수 있는 경우 닫기버튼을 표시합니다.'로 띄어쓰기가 없습니다. 일관성을 맞춰주세요!

2024-07-24 10:04 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +### 루트를 생성했지만 무엇도 표시되지 않습니다 {/*ive-created-a-root-but-nothing-is-displayed*/}
'생성했지만 아무것도'로 수정하는게 좋을 것 같습니다.

2024-07-24 10:04 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +### 다음과 같은 에러가 발생합니다: "대상 컨테이너가 DOM 엘리먼트가 아닙니다" {/*im-getting-an-error-target-container-is-not-a-dom-element*/}
wiki에 의해 '다' 이후에 `:`를 사용하는 것은 지양됩니다. 원래 원문을 유지해주세요!

2024-07-24 10:06 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +경고: root.render(...)에 두 번째 인자를 전달했지만, 이 함수는 하나의 인자만 허용합니다.
root.render(...)는 인라인 코드 블럭(백틱)으로 묶어주세요! ex. `root.render(...)`

2024-07-24 10:06 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +### 다음과 같은 에러가 발생합니다: "함수가 React 자식으로 유효하지 않습니다" {/*im-getting-an-error-functions-are-not-valid-as-a-react-child*/}
ko.react.dev의 wiki에 의해 '다' 이후에 `:`를 사용하는 것을 지양합니다. 원래 원문을 유지해주세요!

2024-07-24 10:10 UTC, lumirlumir requested changes
안녕하세요😊 수고 많으셨습니다.
번역 일관성 관련해서 수정 요청사항이 여러개 있습니다! 참고해서 수정해주시면 감사하겠습니다🙇‍♂️👍

2024-07-25 05:27 UTC, icefoxand commented
앗 알려주신 부분 고쳐서 다시 푸쉬 하겠습니다!! 시간 들여 알려주셔서 너무 감사합니다 ㅠㅠ @lumirlumir

2024-07-27 03:13 UTC, lumirlumir commented on src/content/reference/react-dom/client/createRoot.md
> +같은 루트에서 `render`를 두 번 이상 호출할 수도 있습니다. 컴포넌트의 트리 구조가 이전 렌더링과 일치하는 한 React는 [기존 state를 유지](/learn/preserving-and-resetting-state)합니다. 다음 예제에서 input에 어떻게 타이핑하는지와 무관하게, 매초 반복되는 `render` 호출로 인한 업데이트가 아무런 문
해당 파트는 conflict resolve가 필요하여, 제가 직접 수정하였습니다.

2024-07-29 00:51 UTC, hg-pyun commented on src/content/reference/react-dom/client/createRoot.md
> +  // 닫을 수 있는 경우 닫기버튼을 표시합니다.
```suggestion
  // 닫을 수 있는 경우 닫기 버튼을 표시합니다.
```

2024-07-29 00:51 UTC, hg-pyun commented on src/content/reference/react-dom/client/createRoot.md
> +<CodeStep step={1}>onCaughtError</CodeStep> 옵션은 두개의 인수를 받는 함수입니다.
```suggestion
<CodeStep step={1}>onCaughtError</CodeStep> 옵션은 두 개의 인수를 받는 함수입니다.
```
https://x.com/urimal365/status/327229640278167552

2024-08-06 05:34 UTC, hg-pyun commented
@icefoxand 님 확인 한번 부탁드려요~

2024-08-08 13:43 UTC, icefoxand commented
> @icefoxand 님 확인 한번 부탁드려요~

앗 확인했습니다!! 늦어지게 되어 죄송합니다 ㅠㅠ! 금주내로 다시 제출하겠습니다

2024-08-20 17:47 UTC, closed without merging