Translate: meta
reactjs/ko.react.dev pull request #1044
Opened 2024-09-09 15:15 UTC by Zero-1016

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/universal-style-guide.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/best-practices-for-translation.md)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/translate-glossary.md)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-09-19 14:12 UTC, hg-pyun approved these changes

2024-09-19 14:12 UTC, hg-pyun commented
기여 감사합니다 👍

2024-09-20 13:49 UTC, lumirlumir requested changes
수고 많으셨습니다👍

(다만, #1048 PR 승인  후 textlint 검증 자동화를 통해 검사한 뒤, merge 하는게 좋을 것 같습니다.)

2024-09-21 09:00 UTC, gnujoow approved these changes

2024-09-22 06:43 UTC, lumirlumir approved these changes

2024-09-22 06:44 UTC, merged