fix: ux improvement
reactjs/ko.react.dev pull request #1056
Opened 2024-09-23 03:41 UTC by happyhyep

안녕하세요!
메인 화면에 이런 식으로 단어 단위로 줄바꿈이 되지 않아 UX적으로 좋지 않다는 생각이 들어 수정해보았습니다!

![image](https://github.com/user-attachments/assets/18057c50-b870-47a9-a620-8a40bfb6cbd0)

아래 일본어 페이지를 참고하였고,

![image](https://github.com/user-attachments/assets/7d1c6e22-7a95-4ac4-b008-369c97262a0e)

이런 식으로 수정하였습니다.

![image](https://github.com/user-attachments/assets/2d7c2618-7f72-4ae6-b0e0-70cbbc15253a)

번역이 아니지만 개선해도 되는 부분이 맞다면 다른 페이지와 내용도 개선해보겠습니다!

감사합니다!

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [X] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/universal-style-guide.md)
- [X] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/best-practices-for-translation.md)
- [X] [용어 확인 (Check the term)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/translate-glossary.md)
- [X] [맞춤법 검사 (Spelling check)](https://nara-speller.co.kr/speller/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-09-23 04:30 UTC, lumirlumir requested changes
안녕하세요👍 좋은 제안입니다만 몇가지 수정 요청사항이 있습니다.

1.  `.idea` 디렉토리 내부의 내용은 반영 불가합니다. 삭제 부탁드립니다.
1. 아래 부분도 함께 수정되면 좋지 않을까 합니다.
    ![image](https://github.com/user-attachments/assets/55fe7e01-c74e-49d2-84c4-bfb85ac041e2)
    ![image](https://github.com/user-attachments/assets/7293ec30-b778-4d4d-8dc9-5e2912a2d9d3)
1. 코드 구현 관련해서 수정 요청사항이 있습니다.

2024-09-23 04:32 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +function Br() {
`<Br>` 컴포넌트는 `children`이 없는 래퍼 컴포넌트이므로, 코드 문맥 상 `Para` 컴포넌트와 `Center` 컴포넌트 사이에 코드가 위치하는 것이 더 좋을 것 같습니다.

2024-09-23 04:33 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +function Br() {
`<Br>` 컴포넌트는 `children`이 없는 래퍼 컴포넌트이므로, 코드 문맥 상 `Para` 컴포넌트와 `Center` 컴포넌트 사이에 코드가 위치하는 것이 더 좋을 것 같습니다.

2024-09-23 04:35 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +
`<Br>` 컴포넌트는 `children`이 없는 래퍼 컴포넌트이므로, 코드 문맥 상 `Para` 컴포넌트와 `Center` 컴포넌트 사이에 코드가 위치하는 것이 더 좋을 것 같습니다.

2024-09-23 04:37 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +              <Br /> 사용자 인터페이스 만들기
```suggestion
              컴포넌트를 사용하여
              <Br /> 
              사용자 인터페이스 만들기
```

개행이 있으면 좋을 것 같습니다.

2024-09-23 04:54 UTC, happyhyep commented
넵 감사합니다! 혹시 수정하였는데, 확인해주실 수 있으실까요? @lumirlumir

2024-09-23 05:37 UTC, lumirlumir commented
헉 현재 반응형에서 개행이 잘못된 위치에 발생하는 경우와 띄어쓰기가 안되는 경우가 생기네요...ㅠㅠ

1. 노트북 1024px

![image](https://github.com/user-attachments/assets/576270d4-0d75-4a4f-bdc1-414e7fcc7b7c)

2. 768px 미만

![image](https://github.com/user-attachments/assets/f03db12b-6c1a-47bd-92bf-a81999862841)

2024-09-23 05:39 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +              사용자 인터페이스 만들기
```suggestion
 컴포넌트를 사용하여 <Br /> 사용자 인터페이스 만들기
```

이렇게 한 줄로 쓰면 포맷팅도 깔끔하고 띄어쓰기도 정상 작동합니다

2024-09-23 05:49 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +}
```suggestion
function Br({breakPointPrefix = 'lg'}) {
  return <br className={`hidden ${breakPointPrefix}:inline`} />
}
```
1024px에서 애매하게 줄바꿈이 되는 경우는 위와 같이 컴포넌트 props를 설정해주고, 문제가 있는 아래 코드에서 props를 `'xl'`로 전달해주면 깔끔하게 해결될 것 같습니다.

2024-09-23 05:50 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +                  업그레이드 하기
```suggestion
새로운 기능에 맞춰 <Br breakPointPrefix='xl' /> 업그레이드 하기
```

여기에 props로 `'xl'`을 전달합니다.

2024-09-23 06:54 UTC, happyhyep commented on src/components/Layout/HomeContent.js
> +              사용자 인터페이스 만들기
이건 이렇게 수정한 뒤 푸시하면 자동으로 원래대로 바뀌길래 강제로도 푸쉬해보았습니다만, eslint와 prettier 세팅 때문에 거절되어 변경이 불가능한 것 같습니다 ㅠㅠ 😭

2024-09-23 06:56 UTC, happyhyep commented
넵 감사합니다!!
말씀해주신대로 Pr 태그에 props 추가해보았는데, 이렇게 하면 1223px ~ 1279px에서 반응형이 깨지는 문제가 발생하는 것을 확인하였습니다. 그래서 다른 방식으로 수정해보았는데, 반응형에는 문제가 없는 것 같아 푸시하였습니다!
확인 부탁드리겠습니다 감사합니다! 😊 @lumirlumir

2024-09-23 07:31 UTC, lumirlumir commented
@happyhyep

첫째로, 1221px ~ 1279px에서 문장 길이와 tailwindCSS의 반응형이 맞물리지 않아 아래와 같이 글자가 넘어가는 현상이 있는 것은 확인했습니다.

![image](https://github.com/user-attachments/assets/120695af-1a78-499f-9543-45789a5ee225)

다만, tailwindCSS 규격에 맞지 않는 너무 지엽적인 사이즈까지 고려하여 컴포넌트를 구성하는 것은 너무 과하다고 개인적으로 생각됩니다.  이는 종종 글 자체 내용이 수정될 경우도 발생하기에, 매번 컴포넌트 반응형 사이즈를 조절하는 것은 상당히 비효율적이라 그렇습니다. 따라서, 위 코드 제안에서와 같이 tailwind가 제공하는 반응형 사이즈 안에서만 조절하는 것을 권장합니다.

둘째로, `prettier`와 `eslint`에서 포맷팅 오류가 발생하는 것은 아닙니다. CI에서 해당 테스트가 통과하지 못한 것은 확인했지만, 이는 prettier와 eslint 상의 포맷팅을 맞추지 못했기 때문에 발생하는 것이 아니고, 다른 이유로 발생하는 것입니다. 따라서, `<Br>` 코드를 문장 중간에 넣는 것은 오류를 발생시키지 않습니다.

셋째로, `<Br>` 컴포넌트에 tailwindCSS 속성을 다 빼버리면, 작은 사이즈의 반응형에서 강제 개행이 발생해 버립니다. 아래와 같이 말이죠

![image](https://github.com/user-attachments/assets/270c50ba-5795-4c42-8fe8-7e49c8981f3f)

ja.react.dev에서도 큰 틀에서의 개행만 진행하며, 너무 세세한 부분의 개행까지는 신경쓰지 않기에 결론적으로, 제가 코드 리뷰 해드린 방향으로 수정하시는 것을 권장드립니다.

2024-09-23 07:32 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +}
```suggestion
function Br({breakPointPrefix = 'lg'}) {
  const breakPointClass = {
    lg: 'lg:inline',
    xl: 'xl:inline',
  }[breakPointPrefix];

  return <br className={cn('hidden', breakPointClass)} />;
}
```

이렇게 변경하는 것을 권장합니다.

2024-09-23 07:33 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +              <Br /> 컴포넌트 작성하기
```suggestion
              코드와 마크업으로 <Br /> 컴포넌트 작성하기
```

2024-09-23 07:34 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +              <Br /> 상호작용 요소 추가하기
```suggestion
              필요한 곳에 <Br /> 상호작용 요소 추가하기
```

2024-09-23 07:34 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +              <Br /> 풀스택으로 만들기
```suggestion
              프레임워크를 통해서 <Br /> 풀스택으로 만들기
```

2024-09-23 07:39 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +              컴포넌트를 사용하여 <Br /> 사용자 인터페이스 만들기
```suggestion
              컴포넌트를 사용하여
              <Br /> 사용자 인터페이스 만들기
```

얘도 일관성을 맞춰 수정하는게 좋을 듯 합니다

2024-09-23 13:11 UTC, happyhyep commented
헉 넵 정말 감사합니다!! 댓글 드린다는 걸 깜박했네요 😂
말씀하신 내용으로 수정했습니다! 감사합니다 !! @lumirlumir

2024-09-24 04:00 UTC, lumirlumir commented on src/components/Layout/HomeContent.js
> +  return <br className={cn('hidden', breakPointClass)} />;
```suggestion
  }[breakPointPrefix];
  
  return <br className={cn('hidden', breakPointClass)} />;
```

여기 사이에 공백 하나만 넣어주세요

2024-09-24 05:09 UTC, happyhyep commented on src/components/Layout/HomeContent.js
> +  return <br className={cn('hidden', breakPointClass)} />;
넵 추가했습니다! 감사합니다 ! @lumirlumir

2024-09-24 07:38 UTC, lumirlumir approved these changes
LGTM

2024-09-24 07:39 UTC, merged