docs: Translation for preloadModule.md
reactjs/ko.react.dev pull request #1077
Opened 2024-10-05 10:16 UTC by nyongho11

## Progress

- [] 번역 초안 작성 (Draft translation)
- [X] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/universal-style-guide.md)
- [X] [모범 사례 확인 (Check best practices)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/best-practices-for-translation.md)
- [X] [용어 확인 (Check the term)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/translate-glossary.md)
- [X] [Textlint 가이드 확인 (Check the textlint guide)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/textlint/what-is-textlint.md)
- [X] [맞춤법 검사 (Spelling check)](https://nara-speller.co.kr/speller/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-10-05 12:11 UTC, lumirlumir commented on src/content/reference/react-dom/preloadModule.md
> +* `options`: 객체입니다. 여기에는 다음과 같은 속성이 포함되어 있습니다:
```suggestion
* `options`: 객체입니다. 여기에는 다음과 같은 속성이 포함되어 있습니다.
```

콜론 대신 마침표를 사용해야 합니다.

2024-10-05 12:16 UTC, lumirlumir commented on src/content/reference/react-dom/preloadModule.md
> +  *  `nonce`: 문자열입니다. 엄격한 컨텐츠 보안 정책을 사용할 때 [모듈을 허용하기 위한 암호화 논스](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce)입니다.
```suggestion
  *  `nonce`: 문자열입니다. 엄격한 컨텐츠 보안 정책을 사용할 때 [모듈을 허용하기 위한 암호화 논스(Nonce)](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce)입니다.
```
'논스'는 영어 표현을 그대로 음차하였으므로 괄호 안에 영어 원문을 넣는게 좋을 듯 합니다

2024-10-05 12:20 UTC, lumirlumir commented on src/content/reference/react-dom/preloadModule.md
> +  *  `integrity`: 문자열입니다. 모듈의 [진위 확인](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)을 위한
```suggestion
  *  `integrity`: 문자열입니다. 모듈의 [신뢰성 확인](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)을 위한
```
'신뢰성'이 좀 더 적당한 표현인 것 같습니다

2024-10-05 12:24 UTC, lumirlumir commented on src/content/reference/react-dom/preloadModule.md
> +* 서버 사이드 렌더링이나 서버 컴포넌트를 렌더링할 때, `preloadModule`은 컴포넌트를 렌더링하는 동안 호출하거나, 컴포넌트 렌더링에서 시작된 비동기 컨텍스트 내에서 호출할 때만 효과가 있습니다. 그 외의 호출은 무시됩니다.
```suggestion
* 서버 측 렌더링이나 서버 컴포넌트를 렌더링할 때, `preloadModule`은 컴포넌트를 렌더링하는 동안 호출하거나, 컴포넌트 렌더링에서 시작된 비동기 컨텍스트 내에서 호출할 때만 효과가 있습니다. 그 외의 호출은 무시됩니다.
```

2024-10-05 12:29 UTC, lumirlumir commented on src/content/reference/react-dom/preloadModule.md
> +모듈이 필요한 페이지나 상태로 전환되기 전에 이벤트 핸들러에서 `preloadModule`을 호출하세요. 이렇게 하면 새로운 페이지나 상태를 렌더링할 때 호출하는 것보다 더 일찍 프로세스를 시작할 수 있습니다.
```suggestion
모듈이 필요한 페이지나 State로 전환되기 전에 이벤트 핸들러에서 `preloadModule`을 호출하세요. 이렇게 하면 새로운 페이지나 State를 렌더링할 때 호출하는 것보다 더 일찍 프로세스를 시작할 수 있습니다.
```

2024-10-05 12:30 UTC, lumirlumir requested changes
번역 간 수정 요청사항이 있습니다

2024-10-05 14:10 UTC, nyongho11 commented on src/content/reference/react-dom/preloadModule.md
> +* 서버 사이드 렌더링이나 서버 컴포넌트를 렌더링할 때, `preloadModule`은 컴포넌트를 렌더링하는 동안 호출하거나, 컴포넌트 렌더링에서 시작된 비동기 컨텍스트 내에서 호출할 때만 효과가 있습니다. 그 외의 호출은 무시됩니다.
번역 된 다른 문서들에서도 서버 "사이드" 렌더링과 서버 "측" 렌더링이 혼용되는 것 같습니다. 이에 대한 기준도 있으면 좋을 것 같아요! 🤔

2024-10-05 14:18 UTC, nyongho11 commented on src/content/reference/react-dom/preloadModule.md
> +* `options`: 객체입니다. 여기에는 다음과 같은 속성이 포함되어 있습니다:
원문에는 "... following properties:" 라고 써있었기 때문에 원문의 표기법을 유지할 지, 모범 사례를 적용할 지 고민되었습니다.

2024-10-05 14:26 UTC, nyongho11 commented
리뷰 해주신 내용을 바탕으로 다시 작성했습니다.

2024-10-06 13:21 UTC, lumirlumir commented on src/content/reference/react-dom/preloadModule.md
> +모듈이 필요한 페이지나 State로 전환되기 전에 이벤트 핸들러에서 `preloadModule`을 호출하세요. 이렇게 하면 새로운 페이지나 상태를 렌더링할 때 호출하는 것보다 더 일찍 프로세스를 시작할 수 있습니다.
```suggestion
모듈이 필요한 페이지나 State로 전환되기 전에 이벤트 핸들러에서 `preloadModule`을 호출하세요. 이렇게 하면 새로운 페이지나 State를 렌더링할 때 호출하는 것보다 더 일찍 프로세스를 시작할 수 있습니다.
```

2024-10-06 13:22 UTC, lumirlumir requested changes
하나가 누락되었네요.

그리고 코멘트로 남겨주신 내용들은 현재 반영 작업 중에 있습니다!

2024-10-09 06:24 UTC, nyongho11 commented
@lumirlumir 
누락된 부분 다시 커밋했습니다!

2024-10-09 06:58 UTC, lumirlumir commented
@nyongho11 

제가 요청한 부분과 다른 부분이 수정된 것 같습니다. 다시 한번 확인 부탁드립니다!

2024-10-13 09:01 UTC, nyongho11 commented
@lumirlumir 
다른 부분을 수정하고 커밋했군요 🥲 이번에는 올바르게 수정했습니다!

2024-10-13 09:03 UTC, lumirlumir approved these changes

2024-10-13 09:04 UTC, merged