docs: fix markdown in `cache.md`
reactjs/ko.react.dev pull request #1106
Opened 2024-12-02 15:22 UTC by devwqc

안녕하세요!
`cache.md` 를 읽어보다 Markdown이 제대로 표시되지 않는 부분이 있어서 수정했습니다.

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/universal-style-guide.md)
- [x] [모범 사례 확인 (Check best practices)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/best-practices-for-translation.md)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/translate-glossary.md)
- [x] [Textlint 가이드 확인 (Check the textlint guide)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/textlint/what-is-textlint.md)
- [x] [맞춤법 검사 (Spelling check)](https://nara-speller.co.kr/speller/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-12-02 15:29 UTC, lumirlumir commented on src/content/reference/react/cache.md
> +<CodeStep step={3}>두 번째 호출</CodeStep>에서 Promise가 여전히 _보류 중_ 이면, 결과를 기다리는 동안 `await`가 일시 중지됩니다. 이 최적화는 데이터 불러오기를 기다리는 동안 React가 계산 작업을 계속할 수 있게 해 <CodeStep step={3}>두 번째 호출</CodeStep>에 대한 대기 시간을 줄일 수
```suggestion
<CodeStep step={3}>두 번째 호출</CodeStep>에서 Promise가 여전히 <strong>보류 중</strong>이면, 결과를 기다리는 동안 `await`가 일시 중지됩니다. 이 최적화는 데이터 불러오기를 기다리는 동안 React가 계산 작업을 계속할 수 있게 해 <CodeStep step={3}>두 번째 호출</CodeStep>에 대한 대기 시간을 줄일 수 있게 합니다. 
```

안녕하세요, PR 보내주셔서 감사합니다.

`_`를 사용할 경우 단어 사이에 띄어쓰기를 필수적으로 사용해야 하기에, 대신 `<strong>` 태그를 사용하는게 좋을 듯 합니다!

2024-12-02 15:29 UTC, lumirlumir requested changes
안녕하세요, PR 보내주셔서 감사합니다.

리뷰에 요청사항이 있습니다! 반영해서 수정해주시면 감사하겠습니다

2024-12-02 15:36 UTC, devwqc commented on src/content/reference/react/cache.md
> +<CodeStep step={3}>두 번째 호출</CodeStep>에서 Promise가 여전히 _보류 중_ 이면, 결과를 기다리는 동안 `await`가 일시 중지됩니다. 이 최적화는 데이터 불러오기를 기다리는 동안 React가 계산 작업을 계속할 수 있게 해 <CodeStep step={3}>두 번째 호출</CodeStep>에 대한 대기 시간을 줄일 수
@lumirlumir

좋은 리뷰 감사합니다!

`254 라인` 에서 `보류 중`을 기울임으로 표현하고 있는데 통일성을 위해서 `<strong>` 대신 `<em>` 을 사용하는 것은 어떻게 생각하시나요?

2024-12-02 16:18 UTC, lumirlumir commented on src/content/reference/react/cache.md
> +<CodeStep step={3}>두 번째 호출</CodeStep>에서 Promise가 여전히 _보류 중_ 이면, 결과를 기다리는 동안 `await`가 일시 중지됩니다. 이 최적화는 데이터 불러오기를 기다리는 동안 React가 계산 작업을 계속할 수 있게 해 <CodeStep step={3}>두 번째 호출</CodeStep>에 대한 대기 시간을 줄일 수
@devwqc 아 제가 순간 헷갈렸네요..ㅠㅠ `<em>`으로 해주시면 될 것 같습니다👍

2024-12-02 23:06 UTC, devwqc commented
> 안녕하세요, PR 보내주셔서 감사합니다.
> 
> 리뷰에 요청사항이 있습니다! 반영해서 수정해주시면 감사하겠습니다

@lumirlumir

[984c881](https://github.com/reactjs/ko.react.dev/pull/1106/commits/984c8811f74d5e847906603dd4983afecaece9d6)

감사합니다!
말씀해 주신 부분 반영했습니다.

2024-12-03 04:24 UTC, lumirlumir approved these changes
LGTM, 감사합니다!

2024-12-03 04:24 UTC, merged