Translate: <select>
reactjs/ko.react.dev pull request #597
Opened 2023-04-30 00:31 UTC by this-is-spear

## Progress

- [X] 번역 초안 작성 (Draft translation)
- [X] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [X] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [X] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [X] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-05 05:15 UTC, hg-pyun requested changes
전반적으로 `~하십시오` 같은 하오체가 많이 쓰였는데, 다른 문장과 잘 어울리지 않아서 다듬어 보았습니다. 혹시 더 있다면 바꿔주시면 감사하겠습니다 🙇‍♂️

2023-05-05 05:15 UTC, hg-pyun commented on src/content/reference/react-dom/components/select.md
> +[select box를 제어](#controlling-a-select-box-with-a-state-variable)하려면 `value` prop을 전달하십시오.
```suggestion
[select box를 제어](#controlling-a-select-box-with-a-state-variable)하려면 `value` prop을 전달해주세요.
```

2023-05-05 05:15 UTC, hg-pyun commented on src/content/reference/react-dom/components/select.md
> +`<select>`를 `<label>` 안에 중첩 시킬 수 없다면, 같은 ID를 `<select id>`와 [`<label htmlFor>`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/htmlFor)에 전달하여 연결해야 합니다. 한 컴포넌트에서 여러 인스턴스 간 충돌을 피하려면
```suggestion
`<select>`를 `<label>` 안에 중첩 시킬 수 없다면, 같은 ID를 `<select id>`와 [`<label htmlFor>`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/htmlFor)에 전달하여 연결해야 합니다. 한 컴포넌트에서 여러 인스턴스 간 충돌을 피하려면 [`useId`를 사용하여](/reference/react/useId) ID를 생성해주세요.
```

2023-05-05 05:15 UTC, hg-pyun commented on src/content/reference/react-dom/components/select.md
> +기본적으로 브라우저는 목록에서 첫 번째 `<option>`을 선택합니다. 다른 옵션을 기본값으로 선택하려면 `<select>` 엘리먼트에 `<option>`의 `value`를 `defaultValue`로 전달하십시오.
```suggestion
기본적으로 브라우저는 목록에서 첫 번째 `<option>`을 선택합니다. 다른 옵션을 기본값으로 선택하려면 `<select>` 엘리먼트에 `<option>`의 `value`를 `defaultValue`로 전달해주세요.
```

2023-05-05 05:15 UTC, hg-pyun commented on src/content/reference/react-dom/components/select.md
> +기본적으로 `<form>` 내부의 *모든* `<button>`은 select box의 값을 제출합니다. 의도치 않은 동작으로 인해 당황할 수 있습니다! React 컴포넌트의 사용자 정의 `Button`이 있다면 `<button>` 대신 [`<button type="button">`](https://developer.mozilla.org/en-US/docs
```suggestion
기본적으로 `<form>` 내부의 *모든* `<button>`은 select box의 값을 제출합니다. 의도치 않은 동작으로 인해 당황할 수 있습니다! React 컴포넌트의 사용자 정의 `Button`이 있다면 `<button>` 대신 [`<button type="button">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button)을 반환하는 것을 고려하십시오. 그런 다음 명시적으로 폼을 제출해야 하는 곳에 `<button type="submit">`을 사용해주세요.
```

2023-05-05 05:15 UTC, hg-pyun commented on src/content/reference/react-dom/components/select.md
> +`<select multiple={true}>`를 사용하면 [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData)에서 각 선택한 값을 별도의 이름-값 쌍으로 포함합니다. 위의 예시에서 콘솔 로그를 자세히 살펴보십시오.
```suggestion
`<select multiple={true}>`를 사용하면 [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData)에서 각 선택한 값을 별도의 이름-값 쌍으로 포함합니다. 위의 예시에서 콘솔 로그를 자세히 살펴봐주세요.
```

2023-05-05 05:15 UTC, hg-pyun commented on src/content/reference/react-dom/components/select.md
> +      onChange={e => setSelectedFruit(e.target.value)} // ... 변경 사항에 대해 상태 변수를 업데이트하십시오!
```suggestion
      onChange={e => setSelectedFruit(e.target.value)} // ... 변경 사항에 대해 상태 변수를 업데이트 해주세요!
```

2023-05-05 05:55 UTC, this-is-spear commented
@hg-pyun 피드백 감사합니다! 
`~하십시오`를 사용할 지 고민을 많이 했었는데, 말씀하신 것처럼 자연스럽게 변경할 필요가 있겠네요 ☺️

`~ 해주세요` 보다 `~ 해야 합니다.`로 수정하면 다른 문장들 처럼 `~다`로 끝나 자연스러울 듯 한데, 어떠신가요? 예를 들면 **`value`를 `defaultValue`로 전달해야 합니다.** 처럼 변경할 수 있을 듯 합니다!

2023-05-05 06:07 UTC, this-is-spear commented
@hg-pyun 수정완료했습니다!

2023-05-08 11:07 UTC, hg-pyun approved these changes
반영 감사합니다! LGTM

2023-05-08 11:09 UTC, merged

2023-05-08 11:10 UTC, gnujoow requested changes
<img width="921" alt="image" src="https://user-images.githubusercontent.com/10865414/236808928-358c7adb-d9d1-45d4-a611-23ad423eb3e9.png">
고생하하셧습니다. 문서의 end 라인이 3라인정도 차이나는데 이 부분을 수정해주실 수 있을까요? 원문의 업데이트가 발생했을때 라인넘버를 보면서 확인하는데 원문의 라인넘버를 그대로 유지하면 문서유지에 도움이 됩니다.  @this-is-spear

2023-05-08 11:10 UTC, gnujoow requested changes
<img width="921" alt="image" src="https://user-images.githubusercontent.com/10865414/236808928-358c7adb-d9d1-45d4-a611-23ad423eb3e9.png">
고생하하셧습니다. 문서의 end 라인이 3라인정도 차이나는데 이 부분을 수정해주실 수 있을까요? 원문의 업데이트가 발생했을때 라인넘버를 보면서 확인하는데 원문의 라인넘버를 그대로 유지하면 문서유지에 도움이 됩니다.  @this-is-spear