Translate: <textarea>
reactjs/ko.react.dev pull request #605
Opened 2023-05-01 08:13 UTC by dev-rong

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-02 19:17 UTC, gnujoow commented
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
쌍점을 대부분 그대로 옮겨주신것 같습니다. 위 문서를 참고하셔서 문서스타일 업데이트를 요청드립니다.

2023-05-03 02:06 UTC, dev-rong commented
> * [ ]  [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
>   쌍점을 대부분 그대로 옮겨주신것 같습니다. 위 문서를 참고하셔서 문서스타일 업데이트를 요청드립니다.

2023-05-03 02:12 UTC, dev-rong commented
실수로 닫았다가 다시 엽니다.

2023-05-03 02:14 UTC, dev-rong commented
> * [ ]  [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
>   쌍점을 대부분 그대로 옮겨주신것 같습니다. 위 문서를 참고하셔서 문서스타일 업데이트를 요청드립니다.

리뷰 감사합니다. 반영하였습니다!

2023-05-06 04:16 UTC, MaxKim-J commented on src/content/reference/react-dom/components/textarea.md
> +[`<textarea>` 브라우저 내장 컴포넌트](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)를 사용하면 여러 줄짜리 텍스트 input을 렌더링할 수 있습니다.
`짜리` 가 문어체 문투가 아니라서 표현을 바꾸면 어떨까 싶습니다

```diff
- 여러 줄짜리
+ 여러 줄의
```

2023-05-06 04:16 UTC, MaxKim-J commented on src/content/reference/react-dom/components/textarea.md
> +* `onSelectCapture`: [캡처 단계](/learn/responding-to-events#capture-phase-events)에서 실행되는 `onSelect`의 버전
`버전` 은 꼭 번역되지 않아도 뜻이 통할 것 같습니다. 혹은 `~가 ~의 버전`이다 식으로 번역하는 것도 자연스러워 보입니다.

```diff
- onSelectCapture: 캡처 단계에서 실행되는 `onSelect`의 버전
+ onSelectCapture: 캡처 단계에서 실행되는 `onSelect`
+ onSelectCapture:`onSelect`의 캡처 단계 버전
```

2023-05-06 04:16 UTC, MaxKim-J commented on src/content/reference/react-dom/components/textarea.md
> +폼 필드에 `onChange` 핸들러 없이 `value` prop만 전달하셨습니다. 이렇게 하면 읽기 전용 필드를 렌더링하게 됩니다. 필드가 변경 가능해야 하는 경우 `defaultValue`를 사용하고 그렇지 않은 경우 `onChange` 또는 `readOnly`를 설정하세요.
[모범사례](https://github.com/reactjs/ko.react.dev/wiki/Best-practices-for-translation#%EC%8B%9C%EB%8A%94-%EC%A0%9C%ED%95%9C%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%A9%EB%8B%88%EB%8B%A4) 에 따라 이 부분은 높임 표현을 없애도 좋아보입니다.

```diff
- 폼 필드에 `onChange` 핸들러 없이 `value` prop만 전달하셨습니다.
+ 폼 필드에 `onChange` 핸들러 없이 `value` prop만 전달했습니다.
```

2023-05-08 03:31 UTC, dev-rong commented
@MaxKim-J 리뷰 감사드립니다. 🙂  피드백 주신 대로 수정하는 게 모범사례에 맞고 더 자연스러운 것 같습니다.  또 이후 통일된 용어에 맞춰 reference도 레퍼런스로 수정하였습니다.

2023-05-08 11:10 UTC, hg-pyun approved these changes
확인했습니다. 기여 감사드립니다 🙇‍♂️

2023-05-08 14:03 UTC, gnujoow requested changes
불필요한 개행과 new line feed가 있습니다.

이 부분 수정을 요청드립니다.

2023-05-08 14:03 UTC, gnujoow commented on src/content/reference/react-dom/components/textarea.md
> +React는 `onSelect` 이벤트를 확장하여 선택 사항이 비거나 편집 시 선택 사항에 영향을 끼치게 될 때도 실행됩니다.
```suggestion
* [`onSelect`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/select_event): [`이벤트` 핸들러](/reference/react-dom/components/common#event-handler) 함수. `<textarea>` 내부의 선택 사항이 변경된 후 실행됩니다. React는 `onSelect` 이벤트를 확장하여 선택 사항이 비거나 편집 시 선택 사항에 영향을 끼치게 될 때도 실행됩니다.
```
불필요한 개행이 있습니다.

2023-05-09 10:14 UTC, dev-rong commented
> 불필요한 개행과 new line feed가 있습니다.
> 
> 이 부분 수정을 요청드립니다. 원문이 업데이트 될 때, 원문과 번역의 line number로 비교를합니다. 해서 추후에 업데이트 이력을 더 잘 확인하고자 라인을 맞춰주시면 좋겠습니다.

세심하게 짚어주셔서 감사합니다. 반영했습니다. 🙂

2023-05-10 07:23 UTC, merged