Translate: React DOM Components
reactjs/ko.react.dev pull request #606
Opened 2023-05-01 08:31 UTC by kangju2000

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-02 19:15 UTC, gnujoow requested changes
https://github.com/reactjs/ko.react.dev/wiki/Best-practices-for-translation#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

쌍점을 대부분 그대로 옮겨주신것 같습니다. 위 문서를 참고하셔서 문서스타일 업데이트를 요청드립니다.

2023-05-02 19:20 UTC, gnujoow submitted a review, later dismissed

2023-05-02 19:34 UTC, gnujoow commented on src/content/reference/react-dom/components/index.md
> +`ref`와 `dangerouslySetInnerHTML`같은 React 특정 props를 포함합니다.
의견요청)
`React 특정 props`이란 표현이 `React-specific props`인지, 특정 props를 일컫는것인지 중의적으로 해석 될 수 있습니다. 
위 용어를 `React만의 props` 혹은. `리액트 고유 props` 등으로 수정을 해보면 어떨까요?

2023-05-03 00:50 UTC, kangju2000 commented on src/content/reference/react-dom/components/index.md
> +`ref`와 `dangerouslySetInnerHTML`같은 React 특정 props를 포함합니다.
확실히 `React 특정 props`는 중의적으로 해석될 수 있겠네요!
반영했습니다 :)

2023-05-06 04:19 UTC, MaxKim-J approved these changes
👍🏻

2023-05-07 11:56 UTC, merged