Translate: useTransition
reactjs/ko.react.dev pull request #609
Opened 2023-05-01 16:02 UTC by 1ilsang

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-05 05:07 UTC, hg-pyun commented on src/content/reference/react/useTransition.md
> +### 원치 않는 로딩 표시기 방지 {/*preventing-unwanted-loading-indicators*/}
표시기라는 단어가 어색한데 더 좋은 단어로 바꾸면 어떨까요? 혹은 음역도 괜찮을 것 같다는 생각이 듭니다.

2023-05-05 05:07 UTC, hg-pyun commented on src/content/reference/react/useTransition.md
> +로딩 표시기를 표시하기 위해 전체 탭 컨테이너를 숨기면 사용자 경험이 어색해집니다. `TabButton`에 `useTransition`을 추가하면 탭 버튼에 보류 중인 상태를 표시할 수 있습니다.
위 로딩 표시기와 동문

2023-05-05 18:11 UTC, 1ilsang commented on src/content/reference/react/useTransition.md
> +### 원치 않는 로딩 표시기 방지 {/*preventing-unwanted-loading-indicators*/}
인디케이터를 그대로 사용하는것은 어떨까요? `원치 않는 로딩 인디케이터 방지`

2023-05-09 11:49 UTC, gnujoow commented
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
몇몇 용어들이 업데이트 되었습니다. 확인후 반영 부탁드리겠습니다.

2023-05-09 12:52 UTC, 1ilsang commented
@gnujoow 님 반영되었습니다

2023-05-09 17:29 UTC, gnujoow requested changes
번역 제안은 대부분 정확하고 자연스러운 표현을 사용하고 있습니다. 다만 일부 표현에서 수정되면 이해를 더 쉽게할 수 있는 부분들이 더 있는것 같습니다. 제안해주신 문서를 한번 다시 확인해주시고 이해하기 쉬운 표현으로 바꿔주시면 더 좋을것 같습니다.

2023-05-09 17:29 UTC, gnujoow commented on src/content/reference/react/useTransition.md
> +2. state 업데이트를 transition으로 표시할 수 있는 [`startTransition` 함수](#starttransition)입니다.
```suggestion
1. `isPending` 플래그는 대기 중인 transition이 있는지 알려줍니다.
2. [`startTransition` 함수](#starttransition)는 상태 업데이트를 transition으로 표시할 수 있게 해주는 함수입니다.
```

위 문장들은 useTranstion의 리턴값에 대해서 안내합니다. 각 아이템들이 주어가 되는 번역이 의미를 더 잘 전달합니다.

2023-05-09 17:29 UTC, gnujoow commented on src/content/reference/react/useTransition.md
> +컴포넌트의 최상위 수준에서 `useTransition`을 호출하여 state 업데이트를 non-blocking *transitions*으로 표시하세요.
```suggestion
컴포넌트의 최상위 레벨에서 `useTransition`을 호출하여 state 업데이트를 non-blocking *transitions*으로 표시하세요.
```
수준이라는 표현이 중의적으로 해석될수 있는 여지가 있습니다. 컴포넌트의 위계를 설명하므로 레벨로 음차하는것이 의미 전달을 더 잘한다고 생각합니다.

2023-05-09 17:30 UTC, gnujoow commented on src/content/reference/react/useTransition.md
> +### 원치 않는 로딩 표시기 방지 {/*preventing-unwanted-loading-indicators*/}
@1ilsang 용어에 대한 번역은 이슈를 열어주시면 좋을것 같습니다.
https://github.com/reactjs/ko.react.dev/issues/new/choose

2023-05-11 08:34 UTC, 1ilsang commented on src/content/reference/react/useTransition.md
> +### 원치 않는 로딩 표시기 방지 {/*preventing-unwanted-loading-indicators*/}
@gnujoow 네 https://github.com/reactjs/ko.react.dev/issues/630 오픈했습니다

2023-05-11 08:39 UTC, 1ilsang commented
@gnujoow 님 리뷰 반영했습니다

2023-05-13 02:34 UTC, eomttt approved these changes

2023-05-14 05:45 UTC, hg-pyun approved these changes
LGTM

2023-05-14 05:59 UTC, merged