Translate: isValidElement
reactjs/ko.react.dev pull request #616
Opened 2023-05-03 14:03 UTC by Yoon-Hae-Min

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-05 05:04 UTC, hg-pyun requested changes

2023-05-05 05:04 UTC, hg-pyun commented on src/content/reference/react/isValidElement.md
> +`isValidElement`는 값이 리액트 엘리먼트인지 확인합니다.
React는 원문 그대로 사용하고자 하는 논의가 진행중입니다. #618

2023-05-09 02:20 UTC, Yoon-Hae-Min commented
#618 논의 결과를 적용하였습니다

2023-05-09 17:36 UTC, gnujoow commented on src/content/reference/react/isValidElement.md
> +#### 파라미터 {/*parameters*/}
#614

2023-05-13 01:36 UTC, Yoon-Hae-Min commented
@gnujoow 코멘트 달아 두는걸 깜빡했네요 수정 완료했습니다

2023-05-13 02:35 UTC, eomttt approved these changes

2023-05-14 05:47 UTC, hg-pyun approved these changes

2023-05-14 05:47 UTC, merged