Translate: <useSyncExternalStore>
reactjs/ko.react.dev pull request #619
Opened 2023-05-05 10:05 UTC by HelloMandu

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-08 11:16 UTC, hg-pyun requested changes

2023-05-08 11:16 UTC, hg-pyun commented on src/content/reference/react/useSyncExternalStore.md
> +## 참고 {/*reference*/}
Reference는 레퍼런스로 번역하도록 용어를 정의하고 있습니다. 🙇‍♂️ 

```suggestion
## 레퍼런스 {/*reference*/}
```

2023-05-08 11:16 UTC, hg-pyun commented on src/content/reference/react/useSyncExternalStore.md
> +#### 주의사항 {/*caveats*/}
```suggestion
#### 주의 사항 {/*caveats*/}
```

2023-05-09 17:38 UTC, gnujoow requested changes

2023-05-09 17:38 UTC, gnujoow commented on src/content/reference/react/useSyncExternalStore.md
> -// we recommend using React state instead.
번역이 누락된 부분이 있습니다.

2023-05-14 05:48 UTC, hg-pyun commented on src/content/reference/react/useSyncExternalStore.md
> -// we recommend using React state instead.
@HelloMandu 님 요것만 한번 확인 부탁드려요 🙇‍♂️

2023-05-16 02:46 UTC, hg-pyun approved these changes

2023-05-16 02:46 UTC, hg-pyun commented on src/content/reference/react/useSyncExternalStore.md
> -// we recommend using React state instead.
@gnujoow 님 어프로브 부탁드려요~

2023-05-18 02:05 UTC, merged