Translate : Reusing-logic-with-custom-hooks
reactjs/ko.react.dev pull request #620
Opened 2023-05-05 16:16 UTC by deli-ght

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-09 17:39 UTC, gnujoow commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +리액트는 `useState`, `useContext`, 그리고 `useEffect`과같이 몇몇 내재하고 있는 훅이 존재합니다. 가끔 조금 더 구체적인 목적을 가진 훅이 존재하길 바랄 때도 있을 겁니다. 예를 들어, 데이터를 가져온다던가, 사용자가 온라인 상태인지 계속 확인한다던가, 혹은 채팅방에 연결하기 위한 목적들처럼요. 리액트에서 다음과 같은 훅들을
https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary#%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9A%A9%EC%96%B4
```suggestion
React는 `useState`, `useContext`, 그리고 `useEffect`과같이 몇몇 내재하고 있는 훅이 존재합니다. 가끔 조금 더 구체적인 목적을 가진 훅이 존재하길 바랄 때도 있을 겁니다. 예를 들어, 데이터를 가져온다던가, 사용자가 온라인 상태인지 계속 확인한다던가, 혹은 채팅방에 연결하기 위한 목적들처럼요. 리액트에서 다음과 같은 훅들을 찾기는 어려울 것입니다. 하지만 애플리케이션의 필요에 알맞은 본인만의 훅을 만들 수 있습니다.
```

2023-05-10 07:34 UTC, hg-pyun requested changes
전반적으로 `훅 -> Hook` 으로 바꿔주세요!

2023-05-10 07:34 UTC, hg-pyun commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +title: "커스텀 훅을 이용하는 로직 재사용하기"
Hook은 번역하면 안되는 용어로 등록되어 있습니다.

```suggestion
title: "커스텀 Hook을 이용하는 로직 재사용하기"
```

2023-05-10 07:40 UTC, deli-ght commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +리액트는 `useState`, `useContext`, 그리고 `useEffect`과같이 몇몇 내재하고 있는 훅이 존재합니다. 가끔 조금 더 구체적인 목적을 가진 훅이 존재하길 바랄 때도 있을 겁니다. 예를 들어, 데이터를 가져온다던가, 사용자가 온라인 상태인지 계속 확인한다던가, 혹은 채팅방에 연결하기 위한 목적들처럼요. 리액트에서 다음과 같은 훅들을
네, 감사합니다!

2023-05-10 07:53 UTC, deli-ght commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +title: "커스텀 훅을 이용하는 로직 재사용하기"
감사합니다!

2023-05-10 07:55 UTC, deli-ght commented
왜 빌드 에러가 발생하는지 모르겠네요..

```
> Build error occurred
Error: Export encountered errors on following paths:
        /[[...markdownPath]]: /learn/reusing-logic-with-custom-hooks
    at /Users/minjukim/Documents/ko.react.dev/node_modules/next/dist/export/index.js:405:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/minjukim/Documents/ko.react.dev/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/minjukim/Documents/ko.react.dev/node_modules/next/dist/build/index.js:1230:21
    at async Span.traceAsyncFn (/Users/minjukim/Documents/ko.react.dev/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/minjukim/Documents/ko.react.dev/node_modules/next/dist/build/index.js:1092:17
    at async Span.traceAsyncFn (/Users/minjukim/Documents/ko.react.dev/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/Users/minjukim/Documents/ko.react.dev/node_modules/next/dist/build/index.js:65:29)
error Command failed with exit code 1.
```

2023-05-14 06:25 UTC, eomttt commented
@deli-ght 말씀하신 로컬 에러 때문에 CI가 안되는것 같습니다.
rebase 한번 해보심이...

2023-05-15 01:11 UTC, closed without merging