translate: memo
reactjs/ko.react.dev pull request #634
Opened 2023-05-13 13:46 UTC by yoon-junseo

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-14 06:08 UTC, hg-pyun requested changes

2023-05-14 06:08 UTC, hg-pyun commented on src/content/reference/react/memo.md
> +## 참조 {/*reference*/}
레퍼런스는 음역을 사용해주세요.
```suggestion
## 레퍼런스 {/*reference*/}
```

2023-05-14 06:08 UTC, hg-pyun commented on src/content/reference/react/memo.md
> +### prop가 객체, 배열 또는 함수인 경우 컴포넌트가 리렌더링합니다 {/*my-component-rerenders-when-a-prop-is-an-object-or-array*/}
이 문장이 조금 더 자연스러울 것 같습니다.
```suggestion
### prop가 객체, 배열 또는 함수인 경우 컴포넌트가 리렌더링됩니다. {/*my-component-rerenders-when-a-prop-is-an-object-or-array*/}
```

2023-05-14 06:08 UTC, hg-pyun commented on src/content/reference/react/memo.md
> +`memo`는 새로운 React 컴포넌트를 반환합니다. `memo`에 제공한 컴포넌트와 동일하게 동작하지만, 부모가 리렌더링하더라도 props가 변경되지 않는 한 React는 이를 리렌더링하지 않습니다.
```suggestion
`memo`는 새로운 React 컴포넌트를 반환합니다. `memo`에 제공한 컴포넌트와 동일하게 동작하지만, 부모가 리렌더링되더라도 props가 변경되지 않는 한 React는 이를 리렌더링하지 않습니다.
```

2023-05-14 06:08 UTC, hg-pyun commented on src/content/reference/react/memo.md
> +그 외의 경우에는 컴포넌트를 `memo`로 감싸는 이점이 없습니다. 그렇다고 해서 크게 해가 되지 않기 때문에 일부 팀에서는 개별 사례에 대해 고려하지 않고 가능한 한 많이 메모하는 방식을 선택하기도 합니다. 이 접근 방식은 코드 가독성이 떨어진다는 단점이 있습니다. 또한 모든 메모화가 효과적이지는 않습니다. 항상 새로운 값이 단 하나만 있어도 컴포넌트
```suggestion
그 외의 경우에는 컴포넌트를 `memo`로 감싸는 이점이 없습니다. 그렇다고 해서 크게 해가 되지 않기 때문에 일부 팀에서는 개별 사례에 대해 고려하지 않고 가능한 한 많이 메모하는 방식을 선택하기도 합니다. 이 접근 방식은 코드 가독성이 떨어진다는 단점이 있습니다. 또한 모든 메모화가 효과적이지는 않습니다. 항상 변경되는 값이 하나라도 있다면, 컴포넌트 전체의 메모화를 중단하기에 충분합니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +## 참조 {/*reference*/}
```suggestion
## 레퍼런스 {/*reference*/}
```

https://github.com/reactjs/ko.react.dev/issues/569

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +컴포넌트를 `memo`로 감싸면 해당 컴포넌트의 *메모화된*  버전을 얻을 수 있습니다. 메모화된 버전의 컴포넌트는 일반적으로 부모 컴포넌트가 리렌더링하여도 props가 변경되지 않았다면 리렌더링하지 않습니다. 그러나 메모화는 성능을 최적화하는 것이지 보장하지 않기 때문에 React는 여전히 리렌더링 할 수도 있습니다.
```suggestion
컴포넌트를 `memo`로 감싸면 해당 컴포넌트의 *memoized*  버전을 얻을 수 있습니다. memoized 버전의 컴포넌트는 일반적으로 부모 컴포넌트가 리렌더링하여도 props가 변경되지 않았다면 리렌더링하지 않습니다. 그러나 memoization 은 성능을 최적화하는 것이지 보장하지 않기 때문에 React는 여전히 리렌더링 할 수도 있습니다.
```

메모화된 보단 원문 그대로 memoized  가 더 어울릴것 같네요


그 외에도 memo, memoized, memoization 등이 애매한데 issue 에 등록해봅니다

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +* `Component`: 메모화하려는 컴포넌트입니다. `memo`는 이 컴포넌트를 수정하지 않고 대신 메모화된 새로운 컴포넌트를 반환합니다. 함수와 [`forwardRef`](/reference/react/forwardRef) 컴포넌트를 포함한 모든 유효한 React 컴포넌트가 허용됩니다.
```suggestion
* `Component`:  memoize 하려는 컴포넌트입니다. `memo`는 이 컴포넌트를 수정하지 않고 대신 새로운 memoized 컴포넌트를 반환합니다. 함수와 [`forwardRef`](/reference/react/forwardRef) 컴포넌트를 포함한 모든 유효한 React 컴포넌트가 허용됩니다. 
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +React는 일반적으로 부모가 리렌더링될 때마다 컴포넌트를 리렌더링합니다. `memo`를 사용하면, 새로운 props가 이전 props와 동일하다면 부모가 리렌더링할 때 새로운 props가 이전 props와 동일하면 리런데링하지 않는 컴포넌트를 만들 수 있습니다. 이러한 컴포넌트를 *메모화되었다*고 합니다.
```suggestion
React는 일반적으로 부모가 리렌더링될 때마다 컴포넌트를 리렌더링합니다. `memo`를 사용하면, 새로운 props가 이전 props와 동일하다면 부모가 리렌더링할 때 새로운 props가 이전 props와 동일하면 리렌더링하지 않는 컴포넌트를 만들 수 있습니다. 이러한 컴포넌트를 *memoized*고 합니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +컴포넌트를 메모화하려면 `memo`로 감싸고 기존 컴포넌트 대신에 반환된 값을 사용하세요.
```suggestion
컴포넌트를 memoize 하려면 `memo`로 감싸고 기존 컴포넌트 대신에 반환된 값을 사용하세요.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +이 사이트와 같이 대부분의 인터랙션이 투박한 앱의 경우(페이지 또는 전체 섹션 교체 등) 일반적으로 메모화는 불필요합니다. 반면 앱이 그림 편집기이고 도형 이동과 같이 대부분의 인터랙션이 세분되어 있다면, 메모화가 유용할 수 있습니다.
```suggestion
이 사이트와 같이 대부분의 인터랙션이 투박한 앱의 경우(페이지 또는 전체 섹션 교체 등) 일반적으로 memoization은 불필요합니다. 반면 앱이 그림 편집기이고 도형 이동과 같이 대부분의 인터랙션이 세분되어 있다면, memoization이 유용할 수 있습니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +그 외의 경우에는 컴포넌트를 `memo`로 감싸는 이점이 없습니다. 그렇다고 해서 크게 해가 되지 않기 때문에 일부 팀에서는 개별 사례에 대해 고려하지 않고 가능한 한 많이 메모하는 방식을 선택하기도 합니다. 이 접근 방식은 코드 가독성이 떨어진다는 단점이 있습니다. 또한 모든 메모화가 효과적이지는 않습니다. 항상 새로운 값이 단 하나만 있어도 컴포넌트
```suggestion
그 외의 경우에는 컴포넌트를 `memo`로 감싸는 이점이 없습니다. 그렇다고 해서 크게 해가 되지 않기 때문에 일부 팀에서는 개별 사례에 대해 고려하지 않고 가능한 한 많이 `memo`하는 방식을 선택하기도 합니다. 이 접근 방식은 코드 가독성이 떨어진다는 단점이 있습니다. 또한 모든 memoization이 효과적이지는 않습니다. 항상 새로운 값이 단 하나만 있어도 컴포넌트 전체의 memoization을 중단하기에 충분합니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +**실제로 몇가지 원칙을 따르면 메모화가 불필요할 수 있습니다.**
```suggestion
**실제로 몇가지 원칙을 따르면 memoization이 불필요할 수 있습니다.**
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +3. [렌더링 로직을 순수하게](/learn/keeping-components-pure) 유지하세요. 컴포넌트를 렌더링했을 때 문제가 발생하거나 눈에 띄는 시각적 아티팩트가 생성된다면 컴포넌트에 버그가 있는 것입니다! 메모화하는 대신 버그를 수정하세요.
```suggestion
3. [렌더링 로직을 순수하게](/learn/keeping-components-pure) 유지하세요. 컴포넌트를 렌더링했을 때 문제가 발생하거나 눈에 띄는 시각적 아티팩트가 생성된다면 컴포넌트에 버그가 있는 것입니다! memoziation 하는 대신 버그를 수정하세요.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +5. [Effect에서 불필요한 의존성을 제거](/learn/removing-effect-dependencies)하세요. 예를 들어, 메모화 대신에 일부 객체나 함수를 Effect 내부나 컴포넌트 외부로 이동하는 것이 더 간단할 때가 많습니다.
```suggestion
5. [Effect에서 불필요한 의존성을 제거](/learn/removing-effect-dependencies)하세요. 예를 들어, memoziation 대신에 일부 객체나 함수를 Effect 내부나 컴포넌트 외부로 이동하는 것이 더 간단할 때가 많습니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +특정 인터랙션이 여전히 느리게 느껴진다면 [React 개발자 도구 profiler](https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html)를 사용해 어떤 컴포넌트가 메모화를 통해 가장 큰 이점을 얻을 수 있는지 확인하고 필요한 경우에 메모화 하세요. 이러한 원칙은 컴포
```suggestion
특정 인터랙션이 여전히 느리게 느껴진다면 [React 개발자 도구 profiler](https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html)를 사용해 어떤 컴포넌트가 memoziation을 통해 가장 큰 이점을 얻을 수 있는지 확인하고 필요한 경우에 memoziation 하세요. 이러한 원칙은 컴포넌트를 더 쉽게 디버깅하고 이해할 수 있게 해주므로 어떤 경우든 이 원칙을 따르는 것이 좋습니다. 장기적으로는 이 문제를 완전히 해결하기 위해 [세분된 memoziation을 자동으로 수행하는 방법](https://www.youtube.com/watch?v=lGEMwh32soc)을 연구하고 있습니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +### state를 사용하여 메모화된 컴포넌트 업데이트하기 {/*updating-a-memoized-component-using-state*/}
```suggestion
### state를 사용하여 memoization 된 컴포넌트 업데이트하기 {/*updating-a-memoized-component-using-state*/}
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +컴포넌트가 메모화된 경우에도, 컴포넌트의 state가 변경되면 리렌더링합니다. 메모화는 부모에서 컴포넌트로 전달되는 props에만 적용됩니다.
```suggestion
컴포넌트가 memoziation 된 경우에도, 컴포넌트의 state가 변경되면 리렌더링합니다. 메모화는 부모에서 컴포넌트로 전달되는 props에만 적용됩니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +`memo`를 사용할 때 어떤 prop든 이전의 prop과 *얕은 비교 결과가 같지*  않을 때마다 컴포넌트가 리렌더링 합니다. 즉 React는 [`Object.is`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/is) 비교를 사용하여 컴포넌트의
```suggestion
`memo`를 사용할 때 어떤 prop든 이전의 prop과 *얕은 비교 결과*가 같지  않을 때마다 컴포넌트가 리렌더링 합니다. 즉 React는 [`Object.is`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/is) 비교를 사용하여 컴포넌트의 모든 prop을 이전 값과 비교합니다. `Object.is(3, 3)`는 `true`이지만 `Object.is({}, {})`는 `false`입니다.
```

2023-05-14 06:20 UTC, eomttt commented on src/content/reference/react/memo.md
> +커스텀 `arePropsEqual` 구현을 제공하는 경우 **함수를 포함하여 모든 prop를 비교해야 합니다.** 함수는 종종 부모 컴포넌트의 props와 state를 [클로저로 다룹니다](https://developer.mozilla.org/ko/docs/Web/JavaScript/Closures). `oldProps.onClick !== newProp
```suggestion
`arePropsEqual`를 구현하는 경우 **함수를 포함하여 모든 prop를 비교해야 합니다.** 함수는 종종 부모 컴포넌트의 props와 state를 [클로저로 다룹니다](https://developer.mozilla.org/ko/docs/Web/JavaScript/Closures). `oldProps.onClick !== newProps.onClick`일 때 `true`를 반환하면 컴포넌트가 `onClick` 핸들러 내에서 이전 렌더링의 props와 state를 계속 "인식"하여 매우 혼란스러운 버그가 발생할 수 있습니다.
```

조금 더 문맥에 맞게 봐꿔봤습니다

2023-05-15 01:48 UTC, yoon-junseo commented on src/content/reference/react/memo.md
> +### prop가 객체, 배열 또는 함수인 경우 컴포넌트가 리렌더링합니다 {/*my-component-rerenders-when-a-prop-is-an-object-or-array*/}
@hg-pyun
안녕하세요!
전체적으로 `리렌더링합니다`로 작성했는데 모두 변경하는게 나을지 아니면 코멘트 남겨주신 것만 변경할지 고민 되는데 어떤게 좋을까요?

2023-05-15 01:51 UTC, yoon-junseo commented on src/content/reference/react/memo.md
> +컴포넌트를 `memo`로 감싸면 해당 컴포넌트의 *메모화된*  버전을 얻을 수 있습니다. 메모화된 버전의 컴포넌트는 일반적으로 부모 컴포넌트가 리렌더링하여도 props가 변경되지 않았다면 리렌더링하지 않습니다. 그러나 메모화는 성능을 최적화하는 것이지 보장하지 않기 때문에 React는 여전히 리렌더링 할 수도 있습니다.
@eomttt
용어 등록 issue close 되면 결과에 맞게 수정해두겠습니다.

2023-05-19 03:54 UTC, hg-pyun commented on src/content/reference/react/memo.md
> +### prop가 객체, 배열 또는 함수인 경우 컴포넌트가 리렌더링합니다 {/*my-component-rerenders-when-a-prop-is-an-object-or-array*/}
@yoon-junseo 개인적으로는 모두 변경하는게 어조가 맞을 것 같긴합니다.

2023-05-20 06:36 UTC, eomttt commented
https://github.com/reactjs/ko.react.dev/issues/639

https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary
요거 한번만 확인해주세요

2023-05-21 08:15 UTC, yoon-junseo commented on src/content/reference/react/memo.md
> +### prop가 객체, 배열 또는 함수인 경우 컴포넌트가 리렌더링합니다 {/*my-component-rerenders-when-a-prop-is-an-object-or-array*/}
@hg-pyun 리렌더링 관련 수정했습니다 ~

2023-05-21 08:17 UTC, yoon-junseo commented on src/content/reference/react/memo.md
> +컴포넌트를 `memo`로 감싸면 해당 컴포넌트의 *메모화된*  버전을 얻을 수 있습니다. 메모화된 버전의 컴포넌트는 일반적으로 부모 컴포넌트가 리렌더링하여도 props가 변경되지 않았다면 리렌더링하지 않습니다. 그러나 메모화는 성능을 최적화하는 것이지 보장하지 않기 때문에 React는 여전히 리렌더링 할 수도 있습니다.
@eomttt 위키에 등록된 내용을 바탕으로 용어의 조사에 맞게 내용을 수정했습니다. 다만 남겨주신 리뷰에서 띄어쓰기에 관련한 부분이 일관되지 않아서 임의로 처리를 했는데, 확인해주시면 감사하겠습니다!

2023-05-23 13:08 UTC, hg-pyun approved these changes
LGTM

2023-05-23 13:08 UTC, merged