Translate: renderToNodeStream
reactjs/ko.react.dev pull request #641
Opened 2023-05-14 15:43 UTC by hyew-kim

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-19 04:11 UTC, hg-pyun requested changes
전반적으로 Glossary가 지켜지지 않은 것 같습니다. https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary를 참고해서 체크 부탁드려도 될까요?

2023-05-19 04:11 UTC, hg-pyun commented on src/content/reference/react-dom/server/renderToNodeStream.md
> +## 참조 {/*reference*/}
```suggestion
## 레퍼런스 {/*reference*/}
```

2023-05-19 04:11 UTC, hg-pyun commented on src/content/reference/react-dom/server/renderToNodeStream.md
> +#### 파라미터 {/*parameters*/}
```suggestion
#### 매개변수 {/*parameters*/}
```

2023-05-19 04:11 UTC, hg-pyun commented on src/content/reference/react-dom/server/renderToNodeStream.md
> +#### 주의사항 {/*caveats*/}
```suggestion
#### 주의 사항 {/*caveats*/}
```

2023-05-29 08:36 UTC, hyew-kim commented
Glossary 참조하여 변경해두었습니다. 확인해주시면 감사하겠습니다!

2023-05-29 10:46 UTC, hg-pyun approved these changes

2023-05-29 10:46 UTC, merged

2023-05-29 10:47 UTC, hg-pyun commented
기여 감사합니다. 🙇