Translate : State as a snapshot
reactjs/ko.react.dev pull request #642
Opened 2023-05-14 17:17 UTC by jinyoung234

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-19 04:22 UTC, hg-pyun requested changes

2023-05-19 04:22 UTC, hg-pyun commented on src/content/learn/state-as-a-snapshot.md
> +이 줄은 처음에는 직관적이지 않게 보일 수 있습니다.
기존 번역인 라인이 더 자연스럽게 읽이는 것 같아요.

2023-05-19 04:22 UTC, hg-pyun commented on src/content/learn/state-as-a-snapshot.md
> +* state 설정으로 리렌더링이 촉발되는 방식
```suggestion
* state 설정으로 리렌더링이 동작하는 방식
```

2023-05-19 04:38 UTC, jinyoung234 commented on src/content/learn/state-as-a-snapshot.md
> +이 줄은 처음에는 직관적이지 않게 보일 수 있습니다.
반영 하겠습니다 :)

2023-05-19 04:46 UTC, jinyoung234 commented on src/content/learn/state-as-a-snapshot.md
> +* state 설정으로 리렌더링이 촉발되는 방식
리뷰 해주신 내용들 모두 반영하였습니다 :)

2023-05-20 06:31 UTC, MaxKim-J commented on src/content/learn/state-as-a-snapshot.md
> +State 변수는 읽고 쓸 수 있는 일반 자바스크립트 변수처럼 보일 수 있습니다. 하지만 state는 스냅샷처럼 동작 합니다. state 변수를 설정하여도 이미 가지고 있는 state 변수는 변경되지 않고, 대신 리렌더링이 발동됩니다.
```diff
- state는 스냅샷처럼 동작 합니다. 
+ state는 스냅샷처럼 동작합니다. 
```

2023-05-20 06:31 UTC, MaxKim-J commented on src/content/learn/state-as-a-snapshot.md
> +컴포넌트의 메모리로서 state는 함수가 반환된 후 사라지는 일반 변수와 다릅니다. state는 실제로 함수 외부에 마치 선반에 있는 것처럼 React 자체에 “존재”합니다. React가 컴포넌트를 호출하면 특정 렌더링에 대한 state의 스냅샷을 제공합니다. 컴포넌트는 **해당 렌더링의 state 값을 사용해** 계산된 새로운 props 세트와 이벤트
"도구"의 의미로 쓰인 것 같아서 "로써"가 적합할 것 같네요

```diff
- 컴포넌트의 메모리로서
+ 컴포넌트의 메모리로써
```

2023-05-21 03:26 UTC, jinyoung234 commented on src/content/learn/state-as-a-snapshot.md
> +컴포넌트의 메모리로서 state는 함수가 반환된 후 사라지는 일반 변수와 다릅니다. state는 실제로 함수 외부에 마치 선반에 있는 것처럼 React 자체에 “존재”합니다. React가 컴포넌트를 호출하면 특정 렌더링에 대한 state의 스냅샷을 제공합니다. 컴포넌트는 **해당 렌더링의 state 값을 사용해** 계산된 새로운 props 세트와 이벤트
감사합니다 .. ! 다시 생각해보니 '로써'가 적절한거 같네여 :)

2023-05-21 03:26 UTC, jinyoung234 commented on src/content/learn/state-as-a-snapshot.md
> +State 변수는 읽고 쓸 수 있는 일반 자바스크립트 변수처럼 보일 수 있습니다. 하지만 state는 스냅샷처럼 동작 합니다. state 변수를 설정하여도 이미 가지고 있는 state 변수는 변경되지 않고, 대신 리렌더링이 발동됩니다.
반영 완료했습니다!

2023-05-21 03:58 UTC, eomttt approved these changes

2023-05-23 13:09 UTC, merged