Translate: Your First Component
reactjs/ko.react.dev pull request #645
Opened 2023-05-15 04:43 UTC by nara04040

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-19 03:56 UTC, hg-pyun requested changes

2023-05-19 03:56 UTC, hg-pyun commented on src/content/learn/your-first-component.md
> +기존에는 웹 페이지를 만들 때 웹 개발자가 컨텐츠를 마크업한 다음 JavaScript를 뿌려 상호작용을 추가했습니다. 이는 웹에서 상호작용이 중요했던 시절에 효과적이였습니다. 이제는 많은 사이트와 모든 앱에서 상호작용을 기대합니다. React는 동일한 기술을 사용하면서도 상호작용을 우선시합니다. **React컴포넌트는 *마크업으로 뿌릴 수 있는 JavaS
```suggestion
기존에는 웹 페이지를 만들 때 웹 개발자가 컨텐츠를 마크업한 다음 JavaScript를 뿌려 상호작용을 추가했습니다. 이는 웹에서 상호작용이 중요했던 시절에 효과적이였습니다. 이제는 많은 사이트와 모든 앱에서 상호작용을 기대합니다. React는 동일한 기술을 사용하면서도 상호작용을 우선시합니다. **React 컴포넌트는 *마크업으로 뿌릴 수 있는 JavaScript* 함수입니다.** 그 모습은 다음과 같습니다.(아래 예시는 편집할 수 있습니다.)
```

2023-05-20 06:44 UTC, MaxKim-J commented on src/content/learn/your-first-component.md
> +[React 기반 프레임워크들](/learn/start-a-new-react-project)은 이를 한 단계 더 발전시킵니다. 빈 HTML파일을 사용하고 React가 JavaScript로 페이지 관리를 "대신"하도록 하는 대신, React 컴포넌트에서 HTML을 자동으로 생성하기도합니다. 이를 통해 JavaScript 코드가 로드되기 전에 앱에서 일부 컨
제안) 여기서 "manage"가 javascript가 페이지를 그리고 관리하는 일련의 행위를 포함하기 때문에 "다루다" 정도의 포괄적인 어휘로 대체하면 좀 더 자연스러울 것 같다는 생각입니다.

```diff
- React가 JavaScript로 페이지 관리를 "대신"하도록 하는 대신
+ React가 JavaScript로 페이지를 "다룰 수 있게" 하는 대신
```

2023-05-22 13:32 UTC, nara04040 commented on src/content/learn/your-first-component.md
> +기존에는 웹 페이지를 만들 때 웹 개발자가 컨텐츠를 마크업한 다음 JavaScript를 뿌려 상호작용을 추가했습니다. 이는 웹에서 상호작용이 중요했던 시절에 효과적이였습니다. 이제는 많은 사이트와 모든 앱에서 상호작용을 기대합니다. React는 동일한 기술을 사용하면서도 상호작용을 우선시합니다. **React컴포넌트는 *마크업으로 뿌릴 수 있는 JavaS
좋은 의견 감사합니다! 수정사항 반영하겠습니다!

2023-05-22 13:32 UTC, nara04040 commented on src/content/learn/your-first-component.md
> +[React 기반 프레임워크들](/learn/start-a-new-react-project)은 이를 한 단계 더 발전시킵니다. 빈 HTML파일을 사용하고 React가 JavaScript로 페이지 관리를 "대신"하도록 하는 대신, React 컴포넌트에서 HTML을 자동으로 생성하기도합니다. 이를 통해 JavaScript 코드가 로드되기 전에 앱에서 일부 컨
좋은 의견 감사합니다! 수정사항 반영하겠습니다!

2023-05-23 13:10 UTC, hg-pyun approved these changes

2023-05-23 13:12 UTC, merged