Translate: createFactory
reactjs/ko.react.dev pull request #655
Opened 2023-05-17 16:41 UTC by okcorn

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [x] 리뷰 반영 (Resolve reviews)

2023-05-20 08:30 UTC, MaxKim-J requested changes

2023-05-20 08:30 UTC, MaxKim-J commented on src/content/reference/react/createFactory.md
> +#### 인수 {/*parameters*/}
[grossary](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary#%EC%9D%BC%EB%B0%98)에 따라 "매개변수"로 번역되어야 합니다

2023-05-20 08:30 UTC, MaxKim-J commented on src/content/reference/react/createFactory.md
> +#### 반환 {/*returns*/}
"반환 값" 이 조금더 이해하기 쉬운 것 같습니다

```diff
- #### 반환 {/*returns*/}
+ #### 반환 값 {/*returns*/}
```

2023-05-20 08:30 UTC, MaxKim-J commented on src/content/reference/react/createFactory.md
> +비록 대부분의 React 프로젝트들은 [JSX](/learn/writing-markup-with-jsx)를 사용하여 유저 인터페이스를 그려내지만, JSX가 필수는 아닙니다. 과거에는 `createFactory`를 JSX 없이 유저 인터페이스를 그려낼 방법의 하나로 사용하였습니다.
제안) "describe"가 그려낸다는 표현보다는, "표현"이라는 의미를 전달하고 있다고 생각합니다. 그리고 기본형 표현을 사용해도 무방할 것 같습니다.

```diff
- 비록 대부분의 React 프로젝트들은 [JSX](/learn/writing-markup-with-jsx)를 사용하여 유저 인터페이스를 그려내지만, JSX가 필수는 아닙니다. 과거에는 `createFactory`를 JSX 없이 유저 인터페이스를 그려낼 방법의 하나로 사용하였습니다.
+ 비록 대부분의 React 프로젝트들은 [JSX](/learn/writing-markup-with-jsx)를 사용하여 유저 인터페이스를 표현하지만, JSX가 필수는 아닙니다. 과거에는 `createFactory`를 JSX 없이 유저 인터페이스를 표현하는 방법의 하나로 사용하였습니다.
```

2023-05-20 08:30 UTC, MaxKim-J commented on src/content/reference/react/createFactory.md
> +직접 옮겨와도 상관없을 정도로 `createFactory`를 몇 개 호출하고 있고 JSX를 사용하고 싶지 않다면, [`createElement`](/reference/react/createElement)를 실행하여 팩토리 함수를 대체할 수 있습니다. 예를 들어 이 코드는,
"적은 수의 호출" 이라는 표현의 의도가 드러나야 할 것 같아요. 그리고 문어체 표현을 사용하면 좋을 것 같습니다.

```diff
- 직접 옮겨와도 상관없을 정도로 `createFactory`를 몇 개 호출하고 있고 JSX를 사용하고 싶지 않다면
+ 직접 옮겨와도 무방할 정도로 `createFactory`를 몇 개만 호출하고 있고 JSX를 사용하고 싶지 않다면
```

2023-05-20 08:30 UTC, MaxKim-J commented on src/content/reference/react/createFactory.md
> +JSX에서도 같게 하기 위해서는 `Type`처럼 대문자로 시작하는 변수 이름을 새롭게 설정해야 합니다.
풀어 번역하면 더 명징할 것 같습니다.

```diff
- JSX에서도 같게 하기 위해서는 `Type`처럼 대문자로 시작하는 변수 이름을 새롭게 설정해야 합니다.
+ JSX를 사용해 같은 방식으로 구현한다면 `Type`처럼 대문자로 시작하는 변수 이름을 새롭게 설정해야 합니다.
```

2023-05-20 08:30 UTC, MaxKim-J commented on src/content/reference/react/createFactory.md
> +그렇게 하지 않는 경우 `<type>`이 소문자로 되어있으므로, React는 이것을 내장된 HTML 태그로 해석할 것입니다.
제안) 간결한 문어체 표현이 조금더 자연스러울 것 같습니다.

```diff
- 그렇게 하지 않는 경우 `<type>`이 소문자로 되어있으므로, React는 이것을 내장된 HTML 태그로 해석할 것입니다.
+ 그렇게 하지 않는 경우 React는 소문자로 작성된 `<type>`을 내장된 HTML 태그로 해석할 것입니다.
```

2023-05-26 07:40 UTC, okcorn reviewed
@MaxKim-J 리뷰해주신 부분들 모두 수정 반영 완료하였습니다 ! 천천히 확인 부탁 드립니다.

2023-05-29 10:56 UTC, hg-pyun approved these changes
확인했습니다. 기여 감사합니다 🙇‍♂️

2023-05-31 07:19 UTC, hg-pyun approved these changes

2023-05-31 07:19 UTC, hg-pyun commented
@MaxKim-J 님 확인 부탁드려요 🙇‍♂️

2023-06-01 16:21 UTC, gnujoow approved these changes

2023-06-02 01:07 UTC, MaxKim-J approved these changes
어푸룹이 늦었네요ㅜ 반영 감사합니다! :)

2023-06-02 01:07 UTC, merged