Translate: useId
reactjs/ko.react.dev pull request #661
Opened 2023-05-21 09:17 UTC by mnxmnz

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-21 10:42 UTC, hg-pyun requested changes
기여 감사합니다. 약간 어색한 문장들을 고쳐봤는데 확인해주세요!

2023-05-21 10:42 UTC, hg-pyun commented on src/content/reference/react/useId.md
> +#### useId가 카운터를 증가하는 것보다 나은 이유는 무엇일까요? {/*why-is-useid-better-than-an-incrementing-counter*/}
```suggestion
#### useId의 카운터를 증가하는 것보다 나은 이유는 무엇일까요? {/*why-is-useid-better-than-an-incrementing-counter*/}
```

2023-05-21 10:42 UTC, hg-pyun commented on src/content/reference/react/useId.md
> +### 연관된 여러 개의 엘리먼트의 ID 생성하기 {/*generating-ids-for-several-related-elements*/}
```suggestion
### 여러 개의 연관된 엘리먼트의 ID 생성하기 {/*generating-ids-for-several-related-elements*/}
```

2023-05-21 10:42 UTC, hg-pyun commented on src/content/reference/react/useId.md
> +연관된 여러 개의 엘리먼트에 ID를 전달하는 과정이 필요할 때 `useId`를 사용해서 공유 접두사를 생성할 수 있습니다.
```suggestion 
여러 개의 연관된 엘리먼트에 ID를 전달하는 과정이 필요할 때 `useId`를 사용해서 공유 접두사를 생성할 수 있습니다.
```

2023-05-21 10:42 UTC, hg-pyun commented on src/content/reference/react/useId.md
> +**`useId`를 리스트의 key를 생성하기 위해 사용하면 안 됩니다.** [Key는 데이터에서 생성해야 합니다.](/learn/rendering-lists#where-to-get-your-key)
```suggestion
**`useId`를 리스트의 key를 생성하기 위해 사용하면 안 됩니다.** [Key는 데이터로 부터 생성해야 합니다.](/learn/rendering-lists#where-to-get-your-key)
```

2023-05-21 12:43 UTC, mnxmnz commented on src/content/reference/react/useId.md
> +#### useId가 카운터를 증가하는 것보다 나은 이유는 무엇일까요? {/*why-is-useid-better-than-an-incrementing-counter*/}
@hg-pyun 님 리뷰 감사합니다 🙇‍♀️

다만 수정해 주신 문장에 대해 조금 염려되는 점이 있어서 이에 대해 여쭤보고 싶습니다.

해당 내용은 usdId Hook을 사용하는 것이 전역 변수인 카운터를 사용하는 것보다 더 나은 점을 설명하는 부분인데, "useId의 카운터를 증가하는 것보다 나은 이유는 무엇일까요?"라고 번역했을 때 (useId의 카운터)로 해석되어 useId Hook의 자체적인 카운터로 잘못 해석될까 봐 걱정되어 이 점에 대해 여쭤보고 싶습니다.

리뷰해 주신 거처럼 저도 해당 문장이 어색하다고 생각하는데 혹시 "useId를 사용하는 것이 카운터를 증가하는 것보다 나은 이유는 무엇일까요?"라고 번역하는 것은 어떨지 제안하고 싶습니다.

혹시라도 제가 염려한 것처럼 잘못 해석될 여지가 없다면 수정해 주신 내용으로 반영하겠습니다 :)

2023-05-22 13:43 UTC, mnxmnz commented on src/content/reference/react/useId.md
> +#### useId가 카운터를 증가하는 것보다 나은 이유는 무엇일까요? {/*why-is-useid-better-than-an-incrementing-counter*/}
확인해 주셔서 감사합니다.

해당 문장 포함해서 리뷰해 주신 내용 모두 반영했습니다 :)

2023-05-23 13:02 UTC, merged