Translate: <input>
reactjs/ko.react.dev pull request #666
Opened 2023-05-23 03:49 UTC by SeieunYoo

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-29 11:04 UTC, hg-pyun requested changes

2023-05-29 11:04 UTC, hg-pyun commented on src/content/reference/react-dom/components/input.md
> + [input 을 제어하기 위해서](#controlling-an-input-with-a-state-variable) 아래 props 들 중의 하나를 전달하세요.
```suggestion
[input을 제어하기 위해서](#controlling-an-input-with-a-state-variable) 아래 props 들 중의 하나를 전달하세요.
```

2023-05-29 11:04 UTC, hg-pyun commented on src/content/reference/react-dom/components/input.md
> +### 입력에 라벨 제공하기 {/*providing-a-label-for-an-input*/}
다른 곳에서는 input을 원문 그대로 사용했는데, 이 부분에도 input component를 의미하는 것 같아요. "입력"보다는 "input"으로 번역하는게 더 일관성 있고 자연스러울 것 같습니다. 고유명사 input과 아닌 input(입력)을 명확하게 구분해서 다시한번 확인해주시면 좋을 것 같습니다. 🙇‍♂️ 
```suggestion
input에 라벨 제공하기
```

2023-05-29 11:04 UTC, hg-pyun commented on src/content/reference/react-dom/components/input.md
> +### 입력에 초깃값 제공하기 {/*providing-an-initial-value-for-an-input*/}
```suggestion
### input에 초깃값 제공하기 {/*providing-an-initial-value-for-an-input*/}
```

2023-05-29 11:04 UTC, hg-pyun commented on src/content/reference/react-dom/components/input.md
> +입력의 초깃값은 선택적으로 지정할 수 있습니다. 텍스트 입력을 위한 `defaultValue` 문자열로 전달하세요. 대신 체크박스와 라디오 버튼은 `defaultChecked` 불리언으로 초깃값을 지정해야 합니다.
```suggestion
input의 초깃값은 선택적으로 지정할 수 있습니다. 텍스트 입력을 위한 `defaultValue` 문자열로 전달하세요. 대신 체크박스와 라디오 버튼은 `defaultChecked` 불리언으로 초깃값을 지정해야 합니다.
```

2023-06-05 06:33 UTC, eomttt requested changes

2023-06-05 06:33 UTC, eomttt commented on src/content/reference/react-dom/components/input.md
> +입력을 표시하기 위해 `<input>` 컴포넌트를 렌더링 하세요. 기본적으로 텍스트 입력이 됩니다. 체크박스에는 `type="checkbox"`를, 라디오 버튼에는 `type="radio"` 전달하거나 [다른 입력 타입들 중의 하나](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#inpu
입력 보단 input 이라고 명시하는데 더 좋을것 같네요

2023-06-05 06:33 UTC, eomttt commented on src/content/reference/react-dom/components/input.md
> +### 입력에 라벨 제공하기 {/*providing-a-label-for-an-input*/}
저도 동의하는데요 고유명사 input 을 입력이라고 번역한 부분이 있는데 실제 입력하다 라는 뜻과 중복되지 않도록 고유명사는 input이라고 그대로 쓰는게 더 좋을것 같아요ㅔㅣ

2023-06-08 18:32 UTC, SeieunYoo reviewed
안녕하세요 @eomttt 님 @hg-pyun 님!

남겨주신 리뷰 반영했습니다 🙌

1. `input` 으로 워딩 수정
- [1번](https://github.com/reactjs/ko.react.dev/pull/666/files#diff-9a728e48ee19a69ea9983646d74d8d9d9cc7e0097471f0ad69f4bd04d6861270R316) 과 [2번](https://github.com/reactjs/ko.react.dev/pull/666/files#diff-9a728e48ee19a69ea9983646d74d8d9d9cc7e0097471f0ad69f4bd04d6861270R549) 부분을 제외한 나머지 "입력" 이라는 단어는 "input" 으로 수정했습니다!

2. 맞춤법 및 빠진 부분 수정
- 띄어쓰기 부분 수정했습니다!
- [DOM 관련 부분](https://github.com/reactjs/ko.react.dev/pull/666/files#diff-9a728e48ee19a69ea9983646d74d8d9d9cc7e0097471f0ad69f4bd04d6861270R582) 이 번역에 반영되지 않아 수정했습니다!

2023-06-24 12:52 UTC, eomttt approved these changes

2023-06-26 01:56 UTC, hg-pyun approved these changes
LGTM

2023-06-26 01:57 UTC, merged