Translate: useCallback
reactjs/ko.react.dev pull request #667
Opened 2023-05-24 04:47 UTC by hayoiii

## Progress

- [o] 번역 초안 작성 (Draft translation)
- [o] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [o] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [o] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [o] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-24 09:15 UTC, hg-pyun commented
@hayoiii 님 안녕하세요! 어사인 된 담당자를 인지하지 못하고, 머지해버린 부분 먼저 사죄의 말씀을 드립니다 🙇 
https://github.com/reactjs/ko.react.dev/pull/612#issuecomment-1560452079 에 남겨주신 코멘트를 지금 확인했는데요. 이전에 머지된 PR은 Revert하고, @hayoiii 님께서 번역해주신 걸 우선적으로 반영해보도록 하겠습니다. 감사합니다.

2023-05-29 11:05 UTC, hg-pyun commented
@hayoiii 님, Vercel CI가 현재 실패하고 있는데 확인 부탁드려도 될까요? 아래 코멘트가 도움이 될 것 같습니다. 🙇‍♂️ 
https://github.com/reactjs/ko.react.dev/pull/643#issuecomment-1566707596

2023-05-31 07:36 UTC, hg-pyun commented on src/content/reference/react/useCallback.md
>  #### Parameters {/*parameters*/}
Glossary에 따라 매개변수로 변역하는게 좋을 것 같습니다.

2023-06-01 06:39 UTC, gnujoow requested changes
일부 표현에 대해서 더 자연스러운 표현이 있을것 같습니다. 이번 주중으로 추가 변경 사항을 제안을 올려두겠습니다.

2023-06-01 06:39 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +  // theme이 바뀔때마다 이 것은 새로운 함수가 될 것입니다...
```suggestion
  // theme이 바뀔때마다 다른함수가 될 것입니다...
```

2023-06-01 06:39 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +      {/* ... 그래서 ShippingForm의 props는 절대 같은 값이 될 수 없고, 매번 리렌더링 할 것입니다.*/}
```suggestion
      {/* ... 그래서 ShippingForm의 props는 같은 값이 아니므로 매번 리렌더링 할 것입니다.*/}
```

props가 변경될 때마다 rerender되는것을 강조하면 좋겠습니다.

2023-06-01 06:39 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +  }, [productId, referrer]); // ...이 의존성이 변경되지 않는 한...
```suggestion
  }, [productId, referrer]); // ...이 의존성들이 변경되지 않는 한...
```

2023-06-01 06:39 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +**`handleSubmit`을 `useCallback`으로 감쌈으로써 리렌더링 간에 이것이 (의존성이 변경되기 전까지는) 같은 함수라는 것을 보장합니다.** 특별한 이유가 없다면 함수를 꼭 `useCallback`으로 감쌀 필요는 없습니다. 이 예시에서의 이유는 ['memo'](/reference/react/memo)로 감싼 컴포넌트에 전달하기 때문에
```suggestion
**`handleSubmit`을 `useCallback`으로 감쌈으로써 리렌더링 간에 이것이 (의존성이 변경되기 전까지는) 같은 함수라는 것을 보장합니다.** 특별한 이유가 없다면 함수를 꼭 `useCallback`으로 감쌀 필요는 없습니다. 이 예시에서의 이유는 ['memo'](/reference/react/memo)로 감싼 컴포넌트에 전달하기 때문에 해당 함수가 리렌더링을 건너뛸 수 있기 때문입니다. `useCallback`이 필요한 다른 이유는 이 페이지의 뒷부분에서 설명하겠습니다.
```

2023-06-01 06:39 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +#### 어디에나 useCallback을 추가해야 할까요? {/*should-you-add-usecallback-everywhere*/}
```suggestion
#### 항상 useCallback을 사용해야 할까요? {/*should-you-add-usecallback-everywhere*/}
```

2023-06-01 16:15 UTC, gnujoow requested changes

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +* **`useCallback`은 *함수 자체*를 캐싱합니다.** `useMemo`와 달리, 전달한 함수를 호출하지 않습니다. 그 대신, 전달한 함수를 캐싱해서 `productId`나 `referrer`이 변하지 않으면 `handleSubmit` 자체가 변하지 않도록 합니다. 이것은 불필요하게 `ShippingForm`을 리렌더링하지 않고 `handleS
```suggestion
* **`useCallback`은 *함수 자체*를 캐싱합니다.** `useMemo`와 달리, 전달한 함수를 호출하지 않습니다. 그 대신, 전달한 함수를 캐싱해서 `productId`나 `referrer`이 변하지 않으면 `handleSubmit` 자체가 변하지 않도록 합니다. 이것은 불필요하게 `ShippingForm`을 리렌더링하지 않고 `handleSubmit` 함수를 전달할 수 있도록 해줍니다. 함수의 코드는 사용자가 폼을 제출하기 전까지 실행되지 않을 것입니다.
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +다른 경우에서 `useCallback`으로 함수를 감싸는 것은 아무런 이익이 없습니다. 그렇게 하는 것이 큰 불이익을 가져오지도 않습니다. 그래서 몇몇 팀은 개별적인 경우를 따로 생각하지 않고, 가능한 한 많이 memoization 하는 방식을 택합니다. 단점은 코드의 가독성이 떨어지는 것입니다. 또한, 모든 memoization이 효과적인 것은 아닙니다
```suggestion
다른 경우에서 `useCallback`으로 함수를 감싸는 것은 아무런 이익이 없습니다. 또한 이렇게 하는 것이 큰 불이익을 가져오지도 않으므로  일부 팀은 개별적인 경우를 따로 생각하지 않고, 가능한 한 많이 memoization하는 방식을 택합니다. 단점은 코드의 가독성이 떨어지는 것입니다. 또한, 모든 memoization이 효과적인 것은 아닙니다. "항상 새로운" 하나의 값이 있다면 전체 컴포넌트의 memoization을 깨기에 충분합니다.
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +**실제로, 몇 가지 원칙을 따르면 많은 memoization을 불필요하게 만들 수 있습니다.**
```suggestion
**실제로 몇 가지 원칙을 따르면 많은 memoization을 불필요하게 만들 수 있습니다.**
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +`useCallback`이 함수의 *생성*을 막지 않는다는 점을 주의하세요. 항상 함수를 생성하지만 (이건 괜찮습니다!), 아무것도 변경되지 않았다면 React는 이 것을 무시하고 캐싱된 함수를 돌려줍니다.
```suggestion
`useCallback`이 함수의 *생성*을 막지 않는다는 점을 주의하세요. 항상 함수를 생성하지만 (이건 괜찮습니다!), 그러나 React는 변경이 없는 경우에는 무시하고 캐시된 함수를 반환합니다
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +1. 컴포넌트가 다른 컴포넌트를 시각적으로 감싸고 있다면, [JSX를 자식으로 받게](/learn/passing-props-to-a-component#passing-jsx-as-children) 하세요. 감싸는 컴포넌트가 자신의 상태를 업데이트하면, React는 자식들은 리렌더링할 필요가 없다는 것을 압니다.
```suggestion
1. 컴포넌트가 다른 컴포넌트를 시각적으로 감싸고 있다면 [JSX를 자식으로 받게](/learn/passing-props-to-a-component#passing-jsx-as-children) 하세요. 감싸는 컴포넌트가 자신의 상태를 업데이트하면, React는 자식들은 리렌더링할 필요가 없다는 것을 알게 됩니다.
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +이 예시에서, `ShippingForm` 컴포넌트는 **인위적으로 느리게 만들었기 때문에** 렌더링하는 React 컴포넌트가 실제로 느릴 때 어떤 일이 일어나는 지 볼 수 있습니다. 카운터를 증가시키고 테마를 토글 해보세요.
```suggestion
이 예시에서 `ShippingForm` 컴포넌트는 **인위적으로 느리게 만들었기 때문에** 렌더링하는 React 컴포넌트가 실제로 느릴 때 어떤 일이 일어나는 지 볼 수 있습니다. 카운터를 증가시키고 테마를 토글 해보세요.
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +다음으로, 테마를 토글 해보세요. **`useCallback`을 [`memo`](/reference/react/memo)와 함께 사용한 덕분에, 인위적인 지연에도 불구하고 빠릅니다!** `ShippingForm`은 `handleSubmit` 함수가 변하지 않았기 때문에 리렌더링을 건너뛰었습니다. `productId` 와 `referrer` (`useCal
```suggestion
다음으로 테마를 토글 해보세요. **`useCallback`을 [`memo`](/reference/react/memo)와 함께 사용한 덕분에, 인위적인 지연에도 불구하고 빠릅니다!** `ShippingForm`은 `handleSubmit` 함수가 변하지 않았기 때문에 리렌더링을 건너뛰었습니다. `productId` 와 `referrer` (`useCallback`의 의존성) 모두 마지막 렌더링으로부터 변하지 않았기 때문에 `handleSubmit` 함수도 변하지 않았습니다.
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +이 예시에서, `ShippingForm` 컴포넌트 또한 **인위적으로 느리게 만들었기 때문에** 렌더링하는 React 컴포넌트가 실제로 느릴 때 어떤 일이 일어나는 지 볼 수 있습니다. 카운터를 증가시키고 테마를 토글 해보세요.
```suggestion
이 예시에서 `ShippingForm` 컴포넌트 또한 **인위적으로 느리게 만들었기 때문에** 렌더링하는 React 컴포넌트가 실제로 느릴 때 어떤 일이 일어나는 지 볼 수 있습니다. 카운터를 증가시키고 테마를 토글 해보세요.
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +대신 개별 항목을 컴포넌트로 빼내고 `useCallback`을 거기 안에 넣으세요.
```suggestion
대신 개별 항목을 컴포넌트로 분리하고, 거기에 useCallback을 넣으세요.
```

2023-06-01 16:15 UTC, gnujoow commented on src/content/reference/react/useCallback.md
> +또는, 마지막 스니펫에서 `useCallback`을 제거하고 대신 `Report` 자체를 [`memo`](/reference/react/memo)로 감싸도 됩니다. `item` prop이 변경되지 않으면 `Report`는 리렌더링하지 않기 때문에 `Chart`도 렌더링을 건너뜁니다.
```suggestion
대안으로 마지막 스니펫에서 `useCallback`을 제거하고 대신 `Report` 자체를 [`memo`](/reference/react/memo)로 감싸도 됩니다. `item` prop이 변경되지 않으면 `Report`는 리렌더링하지 않기 때문에 `Chart`도 리렌더링을 건너뜁니다.
```

2023-06-02 15:19 UTC, hayoiii commented on src/content/reference/react/useCallback.md
> +또는, 마지막 스니펫에서 `useCallback`을 제거하고 대신 `Report` 자체를 [`memo`](/reference/react/memo)로 감싸도 됩니다. `item` prop이 변경되지 않으면 `Report`는 리렌더링하지 않기 때문에 `Chart`도 렌더링을 건너뜁니다.
그저 빛... 갓갓 우정님 감사합니다👍🏻

2023-06-03 10:41 UTC, gnujoow approved these changes
LGTM 👍

2023-06-03 12:56 UTC, gnujoow approved these changes

2023-06-03 12:56 UTC, gnujoow approved these changes

2023-06-03 12:57 UTC, merged