Translate/warnings
reactjs/ko.react.dev pull request #674
Opened 2023-05-29 09:44 UTC by donghoon-song

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-05-29 10:54 UTC, hg-pyun commented
CI 체크 부탁드려요. 요 스레드 참고하시면 도움이 될 것 같습니다.
https://github.com/reactjs/ko.react.dev/pull/643#issuecomment-1566707596

2023-05-29 11:11 UTC, donghoon-song commented
@hg-pyun 반영해서 수정은 했는데 계속 안되네요. 제가 권한이 없어서 CI detail을 못 보는데 혹시 첨부해주신 다른 에러가 뜬걸까요?

2023-05-29 11:15 UTC, hg-pyun commented
@donghoon-song 저도 권한이 없어서 CI Detail을 못보고 있습니다.. 흑흑 권한은 Dan만 가지고있는.. 로컬에서 확인할 수 있는 방법을 한번 찾아보겠습니다.

2023-05-29 14:10 UTC, donghoon-song commented
@hg-pyun 해결했어요 감사합니다 :)

2023-05-31 07:42 UTC, hg-pyun requested changes

2023-05-31 07:42 UTC, hg-pyun commented on src/content/warnings/invalid-aria-prop.md
> +title: 유효하지 않은 ARIA 프로퍼티 경고
Prop은 번역하면 안되는 용어로 지정되어 있습니다.
https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary

2023-05-31 07:42 UTC, hg-pyun commented on src/content/warnings/invalid-aria-prop.md
> +1. 유효한 프로퍼티를 사용하고 있다고 생각하는 경우 철자를 주의 깊게 확인해 보세요. `aria-labelledby`와 `aria-activedescendant`는 철자 실수가 잦습니다.
```suggestion
1. 유효한 prop을 사용하고 있다고 생각하는 경우 철자를 주의 깊게 확인해 보세요. `aria-labelledby`와 `aria-activedescendant`는 철자 실수가 잦습니다.
```

2023-06-05 06:52 UTC, eomttt submitted a review, later dismissed
@donghoon-song 
@hg-pyun 님이 남기신 리뷰만 확인 브탁드립니더

2023-06-05 07:11 UTC, donghoon-song commented
@eomttt 반영했습니다 :)

2023-06-11 09:10 UTC, merged