Translate: cloneElement
reactjs/ko.react.dev pull request #680
Opened 2023-05-31 13:10 UTC by onealog

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-06-04 09:13 UTC, MaxKim-J requested changes
원문과 개행이 안 맞는 부분이 2군데 정도 있는 것 같은데 바로잡아주시면 좋을 것 같습니당

2023-06-04 09:13 UTC, MaxKim-J commented on src/content/reference/react/cloneElement.md
> +* `element`: `element` 인자는 유효한 React 엘리먼트여야 합니다. 예를 들어, `<Something />`과 같은 JSX 노드, [`createElement`](/reference/react/createElement)로 호출한 결과물 또는 다른 `cloneElement`로 호출한 결과물이 될 수 있습니다.
제안) 풀어 번역하면 뜻이 명징할 것 같습니다.

```suggestion
* `element`: `element` 인자는 유효한 React 엘리먼트여야 합니다. 예를 들어, `<Something />`과 같은 JSX 노드, [`createElement`](/reference/react/createElement)를 호출해 얻은 결과물 또는 다른 `cloneElement`로 호출해 얻은 결과물이 될 수 있습니다.
```

2023-06-04 09:13 UTC, MaxKim-J commented on src/content/reference/react/cloneElement.md
불필요한 개행이 있습니다

2023-06-04 09:13 UTC, MaxKim-J commented on src/content/reference/react/cloneElement.md
> +일반적으로 컴포넌트에서 엘리먼트를 반환하거나 다른 엘리먼트의 자식으로 만듭니다. 엘리먼트의 프로퍼티를 읽을 수 있지만, 생성된 후에는 모든 엘리먼트를 불투명하게 취급하고 렌더링하는 것이 좋습니다.
제안) "불투명" 이런 직역이 이해를 살짝 어렵게 하는 감이 있어서 의역하면 어떨까 싶습니다.

```suggestion
일반적으로 컴포넌트에서 엘리먼트를 반환하거나 다른 엘리먼트의 자식으로 만듭니다. 엘리먼트의 프로퍼티를 읽을 수 있지만, 생성된 후에는 모든 엘리먼트의 프로퍼티를 읽을 수 없는 것처럼 취급하고 렌더링하는 것이 좋습니다.
```

2023-06-04 09:13 UTC, MaxKim-J commented on src/content/reference/react/cloneElement.md
> +* **자식이 모두 정적으로 알려진 경우에만** `cloneElement(element, null, child1, child2, child3)`와 같이 **자식을 여러 개의 인자로 전달해야 합니다.** 자식이 동적으로 생성되었다면 `cloneElement(element, null, listItems)`와 같이 전체 배열을 세 번째 인자로 전달해야 합니다.
직역하지 않아도 뜻이 통할 것 같습니다.

```suggestion
* **자식이 모두 정적인 경우에만** `cloneElement(element, null, child1, child2, child3)`와 같이 **자식을 여러 개의 인자로 전달해야 합니다.** 자식이 동적으로 생성되었다면 `cloneElement(element, null, listItems)`와 같이 전체 배열을 세 번째 인자로 전달해야 합니다. 이렇게 하면 React가 모든 동적 리스트에 대해 [key가 누락되었다는 경고](/learn/rendering-lists#keeping-list-items-in-order-with-key)를 보여줍니다. 정적 리스트의 경우는 순서가 변경되지 않으므로 이 작업은 필요하지 않습니다.
```

2023-06-04 09:13 UTC, MaxKim-J commented on src/content/reference/react/cloneElement.md
> +## 사용 {/*usage*/}
제안) "사용법" 정도가 단락 제목에 맞는 번역이 아닐까 생각합니다.

```suggestion
## 사용법 {/*usage*/}
```

2023-06-04 09:13 UTC, MaxKim-J commented on src/content/reference/react/cloneElement.md
> +다른 접근 방식으로는 자체 hook을 통해 "비 시각적인" 로직을 추출하는 것을 시도해 볼 수 있습니다. 그리고 hook에 의해서 반환된 정보를 사용하여 렌더링할 내용을 정합니다. 예를 들어 다음과 같이 `useList` 같은 custom hook을 작성할 수 있습니다.
```suggestion
다른 접근 방식으로는 자체 hook을 통해 "비시각적인" 로직을 추출하는 것을 시도해 볼 수 있습니다. 그리고 hook에 의해서 반환된 정보를 사용하여 렌더링할 내용을 정합니다. 예를 들어 다음과 같이 `useList` 같은 custom hook을 작성할 수 있습니다.
```

2023-06-06 09:16 UTC, onealog commented
@MaxKim-J 리뷰 감사합니다 🙂 반영 완료했습니다! 👍

2023-06-16 05:29 UTC, MaxKim-J submitted a review, later dismissed
👍 수고하셨습니다

2023-06-24 12:46 UTC, eomttt reviewed
오타하나 있네요 ㅎㅎ

2023-06-24 12:46 UTC, eomttt commented on src/content/reference/react/cloneElement.md
> +다른 접근 방식으로는 자체 hook을 통해 "비ㅠ시각적인" 로직을 추출하는 것을 시도해 볼 수 있습니다. 그리고 hook에 의해서 반환된 정보를 사용하여 렌더링할 내용을 정합니다. 예를 들어 다음과 같이 `useList` 같은 custom hook을 작성할 수 있습니다.
```suggestion
다른 접근 방식으로는 자체 hook을 통해 "비시각적인" 로직을 추출하는 것을 시도해 볼 수 있습니다. 그리고 hook에 의해서 반환된 정보를 사용하여 렌더링할 내용을 정합니다. 예를 들어 다음과 같이 `useList` 같은 custom hook을 작성할 수 있습니다.
```

2023-06-26 01:57 UTC, hg-pyun commented on src/content/reference/react/cloneElement.md
> +다른 접근 방식으로는 자체 hook을 통해 "비ㅠ시각적인" 로직을 추출하는 것을 시도해 볼 수 있습니다. 그리고 hook에 의해서 반환된 정보를 사용하여 렌더링할 내용을 정합니다. 예를 들어 다음과 같이 `useList` 같은 custom hook을 작성할 수 있습니다.
요건 제가 반영하고 머지하겠습니다 🙇‍♂️

2023-06-26 01:58 UTC, hg-pyun approved these changes
LGTM

2023-06-26 02:03 UTC, merged

2023-06-26 06:38 UTC, onealog commented on src/content/reference/react/cloneElement.md
> +다른 접근 방식으로는 자체 hook을 통해 "비ㅠ시각적인" 로직을 추출하는 것을 시도해 볼 수 있습니다. 그리고 hook에 의해서 반환된 정보를 사용하여 렌더링할 내용을 정합니다. 예를 들어 다음과 같이 `useList` 같은 custom hook을 작성할 수 있습니다.
앗..! 놓쳤네요ㅠ 감사합니다 ㅎㅎ