docs: draft Component translation
reactjs/ko.react.dev pull request #681
Opened 2023-05-31 15:59 UTC by HojinAn

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-06-02 01:05 UTC, hg-pyun requested changes

2023-06-02 01:05 UTC, hg-pyun commented on src/content/reference/react/Component.md
> +함수 컴포넌트로 변환할 때는 `this.context`를 [`useContext`](/reference/react/useContext) 호출로 바꾸세요.
```suggestion
함수 컴포넌트로 변환할 때는 `this.context`를 [`useContext`](/reference/react/useContext) 호출로 바꿔주세요.
```

2023-06-02 01:05 UTC, hg-pyun commented on src/content/reference/react/Component.md
> +일반적으로, 에러에 대한 응답으로 state를 업데이트하고 사용자에게 에러 메시지를 표시할 수 있는 [`static getDerivedStateFromError`](#static-getderivedstatefromerror)와 함께 사용됩니다. 이런 여러 메서드를 사용하는 컴포넌트를 *오차 경계*라고 합니다.
에러 바운더리는 고유명사에 가깝기 때문에 번역하지 않는 편이 좋을 것 같습니다.

```suggestion
일반적으로, 에러에 대한 응답으로 state를 업데이트하고 사용자에게 에러 메시지를 표시할 수 있는 [`static getDerivedStateFromError`](#static-getderivedstatefromerror)와 함께 사용됩니다. 이런 여러 메서드를 사용하는 컴포넌트를 *error boundary*라고 합니다.
```

2023-06-02 01:05 UTC, hg-pyun commented on src/content/reference/react/Component.md
> +`componentDidCatch`는 아무것도 반환해서는 안 됩니다.
```suggestion
`componentDidCatch`는 아무것도 반환하면 안 됩니다.
```

2023-06-02 15:16 UTC, HojinAn reviewed
리뷰 주신 내용 모두 반영했습니다!

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +클래스 컴포넌트에서 `this.props`를 읽는 것은 함수 컴포넌트에서 [props를 선언하는 것](/learn/passing-props-to-a-component#step-2-read-props-inside-the-child-component)와 같습니다.
```suggestion
클래스 컴포넌트에서 `this.props`를 읽는 것은 함수 컴포넌트에서 [props를 선언하는 것](/learn/passing-props-to-a-component#step-2-read-props-inside-the-child-component)과 같습니다.
```

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +* `error`: 발생한 에러입니다. 실제로, 보통은 [`에러`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error)의 인스턴스가 되지만 JavaScript에서 문자열 또는 `null`을 포함한 어떤 값이든 [`던질`](https://developer.m
throw는 예약어인만큼 번역하지 않아도 뜻이 통할 것 같습니다.

```suggestion
* `error`: 발생한 에러입니다. 실제로, 보통은 [`에러`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error)의 인스턴스가 되지만 JavaScript에서 문자열 또는 `null`을 포함한 어떤 값이든 [`throw`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/throw)할 수 있기 때문에 보장되지 않습니다.
```

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +* `info`: 에러에 대한 추가 정보를 포함하는 객체입니다. 이것의 `componentStack` 필드는 모든 부모 컴포넌트의 이름과 출처 위치뿐만 아니라 던진 컴포넌트의 스택 추적을 포함합니다. 프로덕션에서, 컴포넌트의 이름은 최소화됩니다. 프로덕션 에러 보고를 설정하면 일반 JavaScript 에러 스택과 동일한 방법으로 소스맵을 사용하여 컴포넌트
위 코멘트와 같은 맥락으로, 개발에서 사용하는 용어는 번역하지 않아도 뜻이 통할 것 같습니다.

```suggestion
* `info`: 에러에 대한 추가 정보를 포함하는 객체입니다. 이것의 `componentStack` 필드는 모든 부모 컴포넌트의 이름과 출처 위치뿐만 아니라 에러를 throw한 컴포넌트의 stack trace를 포함합니다. 프로덕션에서, 컴포넌트의 이름은 최소화됩니다. 프로덕션 에러 보고를 설정하면 일반 JavaScript 에러 스택과 동일한 방법으로 소스맵을 사용하여 컴포넌트 스택을 디코딩할 수 있습니다.
```

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +* React의 프로덕션과 개발 빌드는 `componentDidCatch`가 에러를 처리하는 방식이 약간 다릅니다. 개발에서는, 에러는 `window`까지 버블업될 것이며, 이는 `window.onerror` 또는 `window.addEventListener('error', callback)`가 `componentDidCatch`에 의해 탐지된 에러를 가
일반적으로 이벤트 처리와 관련된 용어를 사용할때의 용례로 바꿔 번역하면 좋을 것 같습니다. "처리기" 라는 표현 역시 개발에서 사용하는 용어는 번역하지 않아도 뜻이 통할 것 같습니다.

```suggestion
* React의 프로덕션과 개발 빌드는 `componentDidCatch`가 에러를 처리하는 방식이 약간 다릅니다. 개발에서는, 에러는 `window`까지 버블링될 것이며, 이는 `window.onerror` 또는 `window.addEventListener('error', callback)`가 `componentDidCatch`에 의해 탐지된 에러를 가로챈다는 것을 의미합니다. 대신 프로덕션에서, 에러는 버블링되지 않을 것이며, 이는 상위의 에러 핸들러가 `componentDidCatch`에 의해 명시적으로 탐지되지 않은 에러만을 수신하는 것을 의미합니다.
```

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +`UNSAFE_componentWillUpdate`를 정의하면 React는 새 props나 state로 렌더링하기 전에 이를 호출합니다. 이 메서드는 역사적인 이유로만 존재하며 새로운 코드에서 사용하면 안 됩니다. 대신 다른 대안을 사용하세요.
원문과 개행을 맞춰주시면 좋을 것 같습니다

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +- 이름과는 달리, 앱이 [`Suspense`](/reference/react/Suspense)와 같은 최신 React 기능을 사용하는 경우 `UNSAFE_componentWillUpdate`가 컴포넌트가 업데이트*할 것*을 보장하지는 않습니다. 렌더링 시도가 일시 중단되면(예를 들어 일부 하위 컴포넌트의 코드가 아직 로드되지 않았기 때문에) React는
피동 표현이 조금 더 어울리며, 같은 조사(가) 연달아 두 번 나오는 것이 조금 어색합니다.

```suggestion
- 이름과는 달리, 앱이 [`Suspense`](/reference/react/Suspense)와 같은 최신 React 기능을 사용하는 경우 `UNSAFE_componentWillUpdate`는 컴포넌트가 업데이트*될 것*을 보장하지는 않습니다. 렌더링 시도가 일시 중단되면(예를 들어 일부 하위 컴포넌트의 코드가 아직 로드되지 않았기 때문에) React는 진행 중인 트리를 버리고 다음 시도에서 컴포넌트를 처음부터 새로 구성하려고 시도합니다. 다음 렌더링 시도 시에는 props와 state가 달라질 수 있습니다. 이것이 바로 이 메서드가 "안전하지 않은" 이유입니다. 커밋된 업데이트에 대해서만 실행되어야 하는 코드(예: 구독 재설정)는 [`componentDidUpdate`](#componentdidupdate)로 이동해야 합니다.
```

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +* `error`: 던져진 오류입니다. 실제로는 일반적으로 [`Error`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error)의 인스턴스가 되지만, 자바스크립트에서는 문자열이나 심지어 `null`을 포함한 모든 값을 [`throw`](https://dev
위 코멘트와 같습니다

```suggestion
* `error`: throw된 에러입니다. 실제로는 일반적으로 [`Error`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error)의 인스턴스가 되지만, 자바스크립트에서는 문자열이나 심지어 `null`을 포함한 모든 값을 [`throw`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/throw) 할 수 있으므로 보장되지는 않습니다.
```

2023-06-04 09:56 UTC, MaxKim-J commented on src/content/reference/react/Component.md
> +- **prop이 변경될 때 일부 state를 "초기화"** 하려면 컴포넌트를 [완전히 제어](https://ko.legacy.reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-controlled-component)하거나 [key로 완전히 제어
문장이 약간 중의적이어서 명확히 번역하면 좋을 것 같습니다.

```suggestion
- **prop이 변경될 때 일부 state를 "초기화"** 하려면 컴포넌트를 [완전히 제어](https://ko.legacy.reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-controlled-component)하거나 [key를 사용해 완전히 제어하지 않도록](https://ko.legacy.reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) 만드는 것이 좋습니다.
```

2023-06-04 15:59 UTC, HojinAn commented
@MaxKim-J 꼼꼼히 봐주신 내용 모두 반영했습니다! 감사합니다 ㅎㅎ

2023-06-06 06:21 UTC, MaxKim-J approved these changes
내용이 길었는데 고생하셨습니다 👍🏻

2023-06-06 12:24 UTC, hg-pyun approved these changes

2023-06-06 12:25 UTC, merged