Translate: Hooks
reactjs/ko.react.dev pull request #682
Opened 2023-06-04 09:56 UTC by Lee-Seonghyun316

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-06-05 04:56 UTC, eomttt requested changes

2023-06-05 04:56 UTC, eomttt commented on src/content/reference/react/index.md
> +* [`useReducer`](/reference/react/useReducer)는 [리듀서 함수](/learn/extracting-state-logic-into-a-reducer) 내에서 업데이트 로직이 포함된 state 변수를 선언합니다.
reducer 함수 라고 그냥 쓰는것을 추천드려봅니다

2023-06-05 04:56 UTC, eomttt commented on src/content/reference/react/index.md
> +*Refs*는 컴포넌트가 [렌더링에 사용되지 않는 DOM 노드나 타임아웃 ID와 같은 정보](/learn/referencing-values-with-refs)를 보유할 수 있도록 해줍니다. state와 달리 ref를 업데이트하면 컴포넌트를 다시 렌더링하지 않습니다. Refs는 React 패러다임에서의 "탈출"입니다. 내장된 브라우저 API와 같은 Reac
Refs는 DOM 노드나 타임아웃 ID 와 같은 [렌더링에 사용되지 않는 정보] 를 보유할 수 있도록 해줍니다

조금 더 대괄로 내용을 원문과 비슷하게 바꿔보았슴키다

2023-06-05 04:56 UTC, eomttt commented on src/content/reference/react/index.md
> +*Refs*는 컴포넌트가 [렌더링에 사용되지 않는 DOM 노드나 타임아웃 ID와 같은 정보](/learn/referencing-values-with-refs)를 보유할 수 있도록 해줍니다. state와 달리 ref를 업데이트하면 컴포넌트를 다시 렌더링하지 않습니다. Refs는 React 패러다임에서의 "탈출"입니다. 내장된 브라우저 API와 같은 Reac
escape hatch 도 탈출 보다는 원문 그대로 쓰는것을 추천드려봅니더ㅔ

2023-06-05 04:56 UTC, eomttt commented on src/content/reference/react/index.md
> +* [`useImperativeHandle`](/reference/react/useImperativeHandle) 은 컴포넌트가 노출하는 ref를 사용자 정의합니다. 이 기능은 사용 빈도가 낮습니다.
사용자 정의합니다 라는 말 어색한데요

컴포넌트가 노출하는 ref 를 정의합니다 정도로 해도 괜찮아 보이네요

2023-06-05 04:56 UTC, eomttt commented on src/content/reference/react/index.md
> +Effects는 React 패러다임에서의 "탈출"입니다. 애플리케이션의 데이터 흐름을 조율하기 위해 Effects를 사용하지 마세요. 외부 시스템과 상호작용하지 않는다면, [Effect가 필요하지 않을 수도 있습니다.](/learn/you-might-not-need-an-effect)
위에서도 언급 드럈지만 탈출 보단 escape hatch로 원문 그대로 쓰는것을 추천드려봅니드

2023-06-05 04:56 UTC, eomttt commented on src/content/reference/react/index.md
> +- [`useTransition`](/reference/react/useTransition)은 state 전환을 논블로킹으로 표시하고 다른 업데이트를 중단합니다.
번역이 잘못된것 같습니다

다른 업데이트를 중단하는게 아니라 다른 업데이트가 이를 중단 할 수 있다가 되어야할것 같네요

2023-06-06 09:07 UTC, Lee-Seonghyun316 commented
리뷰 감사합니다. 반영하였습니다.

2023-06-13 11:19 UTC, hg-pyun approved these changes

2023-06-24 12:46 UTC, eomttt approved these changes

2023-06-24 12:47 UTC, merged