Translate: Blog/React Labs – June 2022
reactjs/ko.react.dev pull request #696
Opened 2023-06-19 09:10 UTC by juyeong-s

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-06-25 09:58 UTC, MaxKim-J requested changes
불필요한 개행이 있는데 한번 확인해주시면 좋을 것 같아요

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +[React 18](https://reactjs.org/blog/2022/03/29/react-v18) 은 수년간의 준비 끝에 탄생한 버전으로 React 팀에게 귀중한 교훈을 가져다주었습니다. 수년간의 연구와 다양한 경로를 모색한 끝에 출시된 제품입니다. 그 경로 중 일부는 성공적이었지만 더 많은 경로가 막다른 골목에서 새로운 인사이트로 이어졌습니다. 우
`막다른 골목`으로 번역하신 부분 넘 좋네용

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +[React 18](https://reactjs.org/blog/2022/03/29/react-v18) 은 수년간의 준비 끝에 탄생한 버전으로 React 팀에게 귀중한 교훈을 가져다주었습니다. 수년간의 연구와 다양한 경로를 모색한 끝에 출시된 제품입니다. 그 경로 중 일부는 성공적이었지만 더 많은 경로가 막다른 골목에서 새로운 인사이트로 이어졌습니다. 우
아래 문맥과 문서의 성격을 고려했을때, 약간의 의역을 넣으면 어떨까 제안드려봅니다

```suggestion
[React 18](https://reactjs.org/blog/2022/03/29/react-v18) 은 수년간의 준비 끝에 탄생한 버전으로 React 팀에게 귀중한 교훈을 가져다주었습니다. 수년간의 연구와 다양한 경로를 모색한 끝에 출시된 제품입니다. 그 경로 중 일부는 성공적이었지만 더 많은 경로가 막다른 골목에서 새로운 인사이트로 이어졌습니다. 우리가 얻은 한 가지 교훈은 우리가 탐색하고 있는 경로에 대한 인사이트를 공유받지 못한 채 새로운 기능을 기다리는 것은 커뮤니티에 실망감을 준다는 것입니다.
```

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +특히, 우리는 포크된 I/O 라이브러리(예: react-fetch)를 사용하는 아이디어를 포기하고 대신 호환성 향상을 위해 비동기/대기 모델을 채택하고 있습니다. 데이터 불러오기에 라우터를 사용할 수도 있기 때문에 기술적으로 RSC의 릴리스가 차단되지는 않습니다. 또 다른 변화는 파일 확장자 방식에서 벗어나 [경계를 주석](https://github.co
`async/await`은 일반적으로 이해가 가능한 개발 용어에 가까우니 따로 번역하지 않아도 될 것 같습니다. `block`같은 경우는 직역하기보다 의역하면 좋을 것 같습니다.

```suggestion
특히, 우리는 포크된 I/O 라이브러리(예: react-fetch)를 사용하는 아이디어를 포기하고 대신 호환성 향상을 위해 async/await 모델을 채택하고 있습니다. 데이터 불러오기에 라우터를 사용할 수도 있기 때문에 기술적으로 RSC의 릴리스에 지장을 주지는 않습니다. 또 다른 변화는 파일 확장자 방식에서 벗어나 [경계를 주석](https://github.com/reactjs/rfcs/pull/189#issuecomment-1116482278)으로 처리하는 방식을 채택하고 있다는 점입니다.
```

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +현재 스크립트, 외부 스타일, 글꼴 및 이미지와 같은 자산은 일반적으로 외부 시스템을 사용하여 사전 로드되고 로드됩니다. 이로 인해 스트리밍, 서버 컴 등과 같은 새로운 환경에서 조정하기 까다로울 수 있습니다.
웹개발에서 흔히 이야기하는 용어로 바뀌면 이해가 좀 더 쉬울 것 같습니다.

```suggestion
현재 스크립트, 외부 스타일, 글꼴 및 이미지와 같은 리소스는 일반적으로 외부 시스템을 사용하여 사전 로드되고 로드됩니다. 이로 인해 스트리밍, 서버 컴포넌트 등과 같은 새로운 환경에서 조정하기 까다로울 수 있습니다.
```

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +우리는 또한 Suspense를 지원하여 로드될 때까지 표시를 차단하지만 스트리밍 및 동시 렌더링을 차단하지 않는 이미지, CSS 및 글꼴을 가질 수 있도록 하는 것을 고려하고 있습니다. 이것은 시각적 요소가 튀어나오고 레이아웃이 바뀔 때 ["팝코닝"](https://twitter.com/sebmarkbage/status/1516852731251724293
한국어로 발음을 옮기면 해당 용어의 맥락이 모호해져서, 번역하지 않는 것은 어떨까 싶습니다.

```suggestion
우리는 또한 Suspense를 지원하여 로드될 때까지 표시를 차단하지만 스트리밍 및 동시 렌더링을 차단하지 않는 이미지, CSS 및 글꼴을 가질 수 있도록 하는 것을 고려하고 있습니다. 이것은 시각적 요소가 튀어나오고 레이아웃이 바뀔 때 ["popcorning"](https://twitter.com/sebmarkbage/status/1516852731251724293)을 방지하는 데 도움이 될 수 있습니다.
```

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +정적 사이트 생성(SSG)과 증분 정적 재생성(ISR)은 캐시 가능한 페이지의 성능을 얻는 좋은 방법이지만, 특히 일부 콘텐츠는 아니지만 대부분을 캐시할 수 있는 경우 동적 서버 측 렌더링(SSR)의 성능을 개선할 수 있는 기능을 추가할 수 있다고 생각합니다. 컴파일 및 정적 패스를 활용하여 서버 렌더링을 최적화하는 방법을 모색하고 있습니다.
약간 의역하면 뜻이 명확해질 것 같습니다. 불필요한 표현을 없애면 좋을 것 같습니다. 번역의 의미가 원문의 의미와 정확하지 않게 전달되는 부분이 있습니다.

```suggestion
정적 사이트 생성(SSG)과 증분 정적 재생성(ISR)은 캐시 가능한 페이지의 성능을 향상하는 좋은 방법이지만, 동적 서버 측 렌더링(SSR)의 성능을 개선할 수 있는 기능을 더 추가할 수 있다고 생각합니다 - 특히, 대부분의 컨텐츠가 캐싱이 가능하지만 일부만 불가능한 경우를 위해서요. 컴파일 및 정적 패스를 활용하여 서버 렌더링을 최적화하는 방법을 모색하고 있습니다.
```

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +현재 React에는 두 가지 프로파일링 도구가 있습니다. [원래 프로파일러](https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html)는 프로파일링 세션의 모든 커밋에 대한 개요를 보여줍니다. 각 커밋에 대해 렌더링된 모든 컴포넌트와 렌더링하는 데 걸린 시간도 표시됩니다.
문어에 적절하지 않은 표현이 있습니다.

```suggestion
현재 React에는 두 가지 프로파일링 도구가 있습니다. [기존의 프로파일러](https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html)는 프로파일링 세션의 모든 커밋에 대한 개요를 보여줍니다. 각 커밋에 대해 렌더링된 모든 컴포넌트와 렌더링하는 데 걸린 시간도 표시됩니다. 또한 React 18에 도입된 [Timeline Profiler](https://github.com/reactwg/react-18/discussions/76)의 베타 버전이 있는데, 이 기능은 컴포넌트가 업데이트를 예약하는 시기와 React가 이러한 업데이트에서 작동하는 시기를 보여줍니다. 이 두 프로파일러는 개발자가 코드에서 성능 문제를 식별하는 데 도움이 됩니다.
```

2023-06-25 09:58 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +개발자가 개별 느린 커밋이나 context에서 벗어난 컴포넌트에 대해 아는 것은 그다지 유용하지 않다는 것을 깨달았습니다. 실제로 느린 커밋의 원인을 아는 것이 더 유용합니다. 그리고 개발자는 특정 상호 작용(예: 버튼 클릭, 초기 로드 또는 페이지 탐색)을 추적하여 성능 회귀를 관찰하고 상호 작용이 느린 이유와 해결 방법을 이해할 수 있기를 원합니다.
의역을 추가하면 뜻이 좀더 명확해질 것 같습니다. `성능 회귀`라는 표현이 어떤 것을 지칭하는지 모호합니다.

```suggestion
개발자가 각각의 느린 커밋 그 자체의 발생 여부나, context에서 벗어난 컴포넌트에 대해 아는 것은 그다지 유용하지 않다는 것을 깨달았습니다. 실제로 느린 커밋의 원인을 아는 것이 더 유용합니다. 그리고 개발자는 특정 상호 작용(예: 버튼 클릭, 초기 로드 또는 페이지 탐색)을 추적하여 성능을 회귀적으로 관찰하고 상호 작용이 느린 이유와 해결 방법을 이해할 수 있기를 원합니다.
```

2023-06-27 05:56 UTC, juyeong-s commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +[React 18](https://reactjs.org/blog/2022/03/29/react-v18) 은 수년간의 준비 끝에 탄생한 버전으로 React 팀에게 귀중한 교훈을 가져다주었습니다. 수년간의 연구와 다양한 경로를 모색한 끝에 출시된 제품입니다. 그 경로 중 일부는 성공적이었지만 더 많은 경로가 막다른 골목에서 새로운 인사이트로 이어졌습니다. 우
오호 너무 좋습니다

2023-06-27 05:56 UTC, juyeong-s commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +현재 스크립트, 외부 스타일, 글꼴 및 이미지와 같은 자산은 일반적으로 외부 시스템을 사용하여 사전 로드되고 로드됩니다. 이로 인해 스트리밍, 서버 컴 등과 같은 새로운 환경에서 조정하기 까다로울 수 있습니다.
헉 컴포넌트가 빠졌었군요 감사합니다!

2023-06-27 05:56 UTC, juyeong-s commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +우리는 또한 Suspense를 지원하여 로드될 때까지 표시를 차단하지만 스트리밍 및 동시 렌더링을 차단하지 않는 이미지, CSS 및 글꼴을 가질 수 있도록 하는 것을 고려하고 있습니다. 이것은 시각적 요소가 튀어나오고 레이아웃이 바뀔 때 ["팝코닝"](https://twitter.com/sebmarkbage/status/1516852731251724293
저도 번역하면서 고민했던 부분인데, 번역하지 않는게 좋겠네요

2023-06-27 05:56 UTC, juyeong-s commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +개발자가 개별 느린 커밋이나 context에서 벗어난 컴포넌트에 대해 아는 것은 그다지 유용하지 않다는 것을 깨달았습니다. 실제로 느린 커밋의 원인을 아는 것이 더 유용합니다. 그리고 개발자는 특정 상호 작용(예: 버튼 클릭, 초기 로드 또는 페이지 탐색)을 추적하여 성능 회귀를 관찰하고 상호 작용이 느린 이유와 해결 방법을 이해할 수 있기를 원합니다.
오호 확실히 이해하기 쉬워졌네요

2023-07-01 16:26 UTC, hg-pyun approved these changes

2023-07-02 15:59 UTC, MaxKim-J commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +* **즉각적인 전환.** 일부 라우팅 프레임워크는 링크 위로 마우스를 가져갈 때와 같이 후속 탐색 속도를 높이기 위해 이미 데이터를 미리 가져옵니다. 오프스크린을 사용하면 백그라운드에서 다음 화면을 미리 렌더링할 수도 있습니다.
아직 이 밑부터 불필요한 개행이 남아있는 것 같은데요 한번 확인해주세요!

2023-07-05 15:19 UTC, juyeong-s commented on src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md
> +* **즉각적인 전환.** 일부 라우팅 프레임워크는 링크 위로 마우스를 가져갈 때와 같이 후속 탐색 속도를 높이기 위해 이미 데이터를 미리 가져옵니다. 오프스크린을 사용하면 백그라운드에서 다음 화면을 미리 렌더링할 수도 있습니다.
제거했습니다

2023-07-16 07:30 UTC, hg-pyun approved these changes
꼼꼼한번역 감사합니다.

2023-07-16 07:38 UTC, merged