Translate: useDeferredValue
reactjs/ko.react.dev pull request #718
Opened 2023-07-29 02:13 UTC by muroa96

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

useDeferredValue.md 번역입니다.

2023-08-12 12:02 UTC, hg-pyun requested changes

2023-08-12 12:02 UTC, hg-pyun commented on src/content/reference/react/useDeferredValue.md
> +#### 반환 값 {/*returns*/}
```suggestion
#### 반환값 {/*returns*/}
```
아래 이슈에 의거하여 반환값으로 번역 해주시면 좋을 것 같아요!

https://github.com/reactjs/ko.react.dev/issues/725

2023-08-12 12:02 UTC, hg-pyun commented on src/content/reference/react/useDeferredValue.md
> +#### 목록 리렌더링 연기 {/*deferred-re-rendering-of-the-list*/}
전체적으로 연기 보다는 "지연 혹은 지연하기"같은 표현으로 대체하면 어떨까요? 의미상으로 조금 더 와닿을 것 같습니다.

2023-08-13 14:55 UTC, muroa96 commented on src/content/reference/react/useDeferredValue.md
> +#### 목록 리렌더링 연기 {/*deferred-re-rendering-of-the-list*/}
해당 내용 변경했습니다!

2023-08-13 14:59 UTC, muroa96 commented on src/content/reference/react/useDeferredValue.md
> +#### 반환 값 {/*returns*/}
모두 변경했습니다! 또한 시간이 지나고 보니 다소 어색한 부분들이 있는것 같습니다. 추후에 (8월 20일 이내로) 해당 부분들을 추가적으로 수정하여 PR을 드려도 괜찮을까요?

2023-08-19 04:11 UTC, hg-pyun approved these changes
LGTM

2023-08-19 04:11 UTC, merged