Translate: Legacy API - Children
reactjs/ko.react.dev pull request #724
Opened 2023-08-03 15:00 UTC by mjjomdev

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-08-12 16:19 UTC, hg-pyun requested changes

2023-08-12 16:19 UTC, hg-pyun commented on src/content/reference/react/Children.md
> +#### 반환 {/*children-count-returns*/}
반환값으로 번역해주세요!

```suggestion
#### 반환값 {/*children-count-returns*/}
```

2023-08-12 16:19 UTC, hg-pyun commented on src/content/reference/react/Children.md
> +#### 반환 {/*children-foreach-returns*/}
```suggestion
#### 반환값 {/*children-foreach-returns*/}
```

2023-08-12 16:19 UTC, hg-pyun commented on src/content/reference/react/Children.md
> +#### 반환 {/*children-only-returns*/}
```suggestion
#### 반환값 {/*children-only-returns*/}
```

2023-08-12 16:19 UTC, hg-pyun commented on src/content/reference/react/Children.md
> +#### 반환 {/*children-toarray-returns*/}
```suggestion
#### 반환값 {/*children-toarray-returns*/}
```

2023-08-13 12:11 UTC, mjjomdev commented on src/content/reference/react/Children.md
> +#### 반환 {/*children-toarray-returns*/}
@hg-pyun 리뷰 감사합니다. 모두 수정했습니다 :)

2023-08-19 04:11 UTC, hg-pyun approved these changes
LGTM

2023-08-19 04:11 UTC, merged