Translate: renderToReadableStream
reactjs/ko.react.dev pull request #774
Opened 2023-09-17 13:08 UTC by Jay-WKJun

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2023-09-18 12:44 UTC, hg-pyun commented
늦어서 죄송합니다. 내일 리뷰해보겠습니다 🙏

2023-09-23 01:07 UTC, hg-pyun requested changes
PR본문에 있는 체크리스트를 한번 확인한 후에 다시 리뷰요청 부탁드려요!

2023-09-23 01:07 UTC, hg-pyun commented on src/content/reference/react-dom/server/renderToReadableStream.md
>  #### Returns {/*returns*/}
반환값으로 번역해주세요.

2023-09-23 01:07 UTC, hg-pyun commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +리액트는 [doctype](https://developer.mozilla.org/en-US/docs/Glossary/Doctype)와 <CodeStep step={2}>bootstrap `<script>` 태그들</CodeStep>을 결과 HTML 스트림에 주입합니다:
리액트는 번여하면 안되는 용어에 포함되어 있습니다.

2023-09-23 01:07 UTC, hg-pyun commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +서버에선 `<App assetMap={assetMap} />`을 렌더하고, 에셋 URL들과 함께 `assetMap`을 전달합니다:
"render는 랜더링하다"로 번역해주세요.

2023-09-27 11:28 UTC, Jay-WKJun commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +서버에선 `<App assetMap={assetMap} />`을 렌더하고, 에셋 URL들과 함께 `assetMap`을 전달합니다:
수정되었습니다.

[622240e](https://github.com/reactjs/ko.react.dev/pull/774/commits/622240ef798a32e43d9c94e3f7f270a0b507f65f)

2023-09-27 11:28 UTC, Jay-WKJun commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +리액트는 [doctype](https://developer.mozilla.org/en-US/docs/Glossary/Doctype)와 <CodeStep step={2}>bootstrap `<script>` 태그들</CodeStep>을 결과 HTML 스트림에 주입합니다:
수정되었습니다.

[b682fc3](https://github.com/reactjs/ko.react.dev/pull/774/commits/b682fc3c8ef2829258c091b565508a02b84a7370)

2023-09-27 11:28 UTC, Jay-WKJun commented on src/content/reference/react-dom/server/renderToReadableStream.md
>  #### Returns {/*returns*/}
수정되었습니다.

[b682fc3](https://github.com/reactjs/ko.react.dev/pull/774/commits/b682fc3c8ef2829258c091b565508a02b84a7370)

2023-10-03 12:38 UTC, hg-pyun approved these changes

2023-10-03 12:39 UTC, merged