translate: Hooks
reactjs/ko.react.dev pull request #865
Opened 2024-02-19 13:39 UTC by coddingyun

https://github.com/reactjs/ko.react.dev/issues/859#issue-2122246149 에 해당하는 [Hook 훑어보기] 번역을 진행하였습니다.

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-02-27 02:59 UTC, hg-pyun requested changes
리뷰가 늦었습니다 🙏 전반적으로 번역을 잘 해주셔서 감사합니다. 

기존에 타이틀 이름으로 Hooks로 쓰인 부분을 Hook으로 번역해 주셨는데, 이 부분은 원문을 따라가는게 더 좋지 않을까 싶어서 제안드려봅니다.

2024-02-27 02:59 UTC, hg-pyun commented on src/content/reference/react/hooks.md
> +## Context Hook {/*context-hooks*/}
여기는 원문 그대로 Hooks를 그대로 쓰면 어떨까요?

2024-02-27 02:59 UTC, hg-pyun commented on src/content/reference/react/hooks.md
> +## Effect Hook {/*effect-hooks*/}
여기도 hooks

2024-02-27 02:59 UTC, hg-pyun commented on src/content/reference/react/hooks.md
> +Effect는 React 패러다임의 "탈출구"입니다. 애플리케이션의 데이터 흐름을 조정하기 위해 Effect를 쓰지 마세요. 외부 시스템과 상호작용하지 않는다면, [Effect가 필요하지 않을 수도 있습니다.](/learn/you-might-not-need-an-effect)
```suggestion
Effects는 React 패러다임의 "탈출구"입니다. 애플리케이션의 데이터 흐름을 조정하기 위해 Effect를 쓰지 마세요. 외부 시스템과 상호작용하지 않는다면, [Effect가 필요하지 않을 수도 있습니다.](/learn/you-might-not-need-an-effect)
```

2024-02-27 02:59 UTC, hg-pyun commented on src/content/reference/react/hooks.md
> +## Performance Hook {/*performance-hooks*/}
hooks

2024-02-27 02:59 UTC, hg-pyun commented on src/content/reference/react/hooks.md
> +## Resource Hook {/*resource-hooks*/}
hooks

2024-02-27 02:59 UTC, hg-pyun commented on src/content/reference/react/hooks.md
> +## 기타 Hook {/*other-hooks*/}
hooks

2024-02-27 03:13 UTC, eomttt commented
hello

[Hyuntae Eom - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2hh6ml)	[2hh6ml]

On February 27, 2024 at 2:59 GMT, Haegul Pyun ***@***.***> wrote:

@hg-pyun requested changes on this pull request.

리뷰가 늦었습니다 🙏 전반적으로 번역을 잘 해주셔서 감사합니다.

기존에 타이틀 이름으로 Hooks로 쓰인 부분을 Hook으로 번역해 주셨는데, 이 부분은 원문을 따라가는게 더 좋지 않을까 싶어서 제안드려봅니다.
---------------------------------------------------------------

In [src/content/reference/react/hooks.md](https://github.com/reactjs/ko.react.dev/pull/865#discussion_r1503570303):
> @@ -27,11 +27,12 @@ function ImageGallery() { --- -## Context Hooks {/*context-hooks*/} +## Context Hook {/*context-hooks*/}
여기는 원문 그대로 Hooks를 그대로 쓰면 어떨까요?
---------------------------------------------------------------

In [src/content/reference/react/hooks.md](https://github.com/reactjs/ko.react.dev/pull/865#discussion_r1503570641):
> @@ -56,11 +57,11 @@ function Form() { --- -## Effect Hooks {/*effect-hooks*/} +## Effect Hook {/*effect-hooks*/}
여기도 hooks
---------------------------------------------------------------

In [src/content/reference/react/hooks.md](https://github.com/reactjs/ko.react.dev/pull/865#discussion_r1503570878):
> @@ -72,23 +73,23 @@ function ChatRoom({ roomId }) { // ... ``` -Effects are an "escape hatch" from the React paradigm. Don't use Effects to orchestrate the data flow of your application. If you're not interacting with an external system, [you might not need an Effect.](/learn/you-might-not-need-an-effect) +Effect는 React 패러다임의 "탈출구"입니다. 애플리케이션의 데이터 흐름을 조정하기 위해 Effect를 쓰지 마세요. 외부 시스템과 상호작용하지 않는다면, [Effect가 필요하지 않을 수도 있습니다.](/learn/you-might-not-need-an-effect)  ⬇️ Suggested change -Effect는 React 패러다임의 "탈출구"입니다. 애플리케이션의 데이터 흐름을 조정하기 위해 Effect를 쓰지 마세요. 외부 시스템과 상호작용하지 않는다면, [Effect가 필요하지 않을 수도 있습니다.](/learn/you-might-not-need-an-effect) +Effects는 React 패러다임의 "탈출구"입니다. 애플리케이션의 데이터 흐름을 조정하기 위해 Effect를 쓰지 마세요. 외부 시스템과 상호작용하지 않는다면, [Effect가 필요하지 않을 수도 있습니다.](/learn/you-might-not-need-an-effect)  ---------------------------------------------------------------

In [src/content/reference/react/hooks.md](https://github.com/reactjs/ko.react.dev/pull/865#discussion_r1503570975):
> --- -## Performance Hooks {/*performance-hooks*/} +## Performance Hook {/*performance-hooks*/}
hooks
---------------------------------------------------------------

In [src/content/reference/react/hooks.md](https://github.com/reactjs/ko.react.dev/pull/865#discussion_r1503571135):
> --- -## Resource Hooks {/*resource-hooks*/} +## Resource Hook {/*resource-hooks*/}
hooks
---------------------------------------------------------------

In [src/content/reference/react/hooks.md](https://github.com/reactjs/ko.react.dev/pull/865#discussion_r1503571193):
> @@ -124,16 +125,15 @@ function MessageComponent({ messagePromise }) { --- -## Other Hooks {/*other-hooks*/} +## 기타 Hook {/*other-hooks*/}
hooks

—
Reply to this email directly, [view it on GitHub](https://github.com/reactjs/ko.react.dev/pull/865#pullrequestreview-1902424369), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AFML5QICQO4V7FJSNTVFGHDYVVDYPAVCNFSM6AAAAABDPPRBKCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMBSGQZDIMZWHE).
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-02-27 12:09 UTC, coddingyun commented
피드백 반영하여 모두 hook -> hooks로 수정하였습니다!

2024-02-27 12:22 UTC, hg-pyun approved these changes
LGTM

2024-03-02 09:53 UTC, merged

2024-03-02 09:54 UTC, hg-pyun commented
@coddingyun 머지하겠습니다 🙇‍♂️