Translate: what weve been working on february 2024
reactjs/ko.react.dev pull request #900
Opened 2024-04-28 17:58 UTC by shyuuuuni

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-04-29 02:29 UTC, hg-pyun approved these changes
기여 감사합니다!

2024-04-29 02:30 UTC, hg-pyun requested changes
JavaScript와 자바스크립트 표기가 혼용되고 있는데, 하나로 통일하면 좋을 것 같습니다.

2024-04-29 02:30 UTC, hg-pyun commented on src/content/blog/2024/02/15/react-labs-what-we-have-been-working-on-february-2024.md
> +수동 memoization는 합리적인 절충안이지만, 우리는 만족하지 않았습니다. 우리의 비전은 state 변경 시 React가 *핵심적인 멘탈 모델을 손상하지 않으면서* UI의 정확한 부분만 *자동으로* 다시 렌더링하는 것입니다. 우리는 UI가 표준 Javascript 값과 패턴으로 이루어진 state의 단순한 함수라고 생각하는 React의 접근 방식이
```suggestion
수동 memoization는 합리적인 절충안이지만, 우리는 만족하지 않았습니다. 우리의 비전은 state 변경 시 React가 *핵심적인 멘탈 모델을 손상하지 않으면서* UI의 정확한 부분만 *자동으로* 다시 렌더링하는 것입니다. 우리는 UI가 표준 JavaScript 값과 패턴으로 이루어진 state의 단순한 함수라고 생각하는 React의 접근 방식이 바로 수많은 개발자가 React에 쉽게 접근할 수 있었던 핵심 이유라고 생각합니다. 이것이 우리가 React를 위한 최적화 컴파일러를 구축하기 위해 투자한 이유입니다.
```

2024-04-29 02:30 UTC, hg-pyun commented on src/content/blog/2024/02/15/react-labs-what-we-have-been-working-on-february-2024.md
> +Javascript는 느슨한 규칙과 동적인 특징 때문에 최적화하기에 매우 까다로운 언어입니다. React 컴파일러는 JavaScript 규칙과 *함께* "React 규칙"을 모두 모델링하여 코드를 안전하게 컴파일할 수 있습니다. 예를 들어, React 컴포넌트는 동일한 입력이 주어지면 동일한 값을 반환하는 멱등성을 만족해야 하며, props나 state를
```suggestion
JavaScript는 느슨한 규칙과 동적인 특징 때문에 최적화하기에 매우 까다로운 언어입니다. React 컴파일러는 JavaScript 규칙과 *함께* "React 규칙"을 모두 모델링하여 코드를 안전하게 컴파일할 수 있습니다. 예를 들어, React 컴포넌트는 동일한 입력이 주어지면 동일한 값을 반환하는 멱등성을 만족해야 하며, props나 state를 변경시키지 못합니다. 이러한 규칙은 개발자가 작업할 수 있는 범위를 제한하고 컴파일러가 최적화할 수 있는 안전한 공간을 만들어 나가는 데 도움을 줍니다.
```

2024-04-29 12:30 UTC, shyuuuuni commented
> JavaScript와 자바스크립트 표기가 혼용되고 있는데, 하나로 통일하면 좋을 것 같습니다.

리뷰 감사합니다! 제안해주신 `Javascript` 오타 커밋 반영 및 `자바스크립트`로 미번역한 용어 번역했습니다. 👍

2024-05-12 04:08 UTC, hg-pyun commented
@shyuuuuni 휴가가 길어서 리뷰가 늦었습니다 🙇‍♂️ 컨플릭트 한번 풀어주실 수 있으실까요?

2024-05-14 04:30 UTC, shyuuuuni commented
> @shyuuuuni 휴가가 길어서 리뷰가 늦었습니다 🙇‍♂️ 컨플릭트 한번 풀어주실 수 있으실까요?

@hg-pyun 오 넵넵 아래 변경사항 확인하고 반영했습니다!
- 포스트 설명 추가
- 훅 이름 변경 반영 (`useFormState` -> u`seActionState`)
- 'use server' 및 'use client' 라우팅 변경 (`/react` -> `/rsc`)

2024-05-15 16:33 UTC, gnujoow approved these changes

2024-05-20 03:42 UTC, hg-pyun approved these changes

2024-05-20 03:42 UTC, merged