translate: experimental_useEffectEvent.md
reactjs/ko.react.dev pull request #903
Opened 2024-05-03 06:36 UTC by songjung-good

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-05-03 16:30 UTC, taggon requested changes

2024-05-03 16:30 UTC, taggon commented on src/content/reference/react/experimental_useEffectEvent.md
> +가장 최신 버전의 recent experimental 버전으로 업그레이드하여 사용해 볼 수 있습니다.
번역 수정이 필요한 듯 보입니다. experimental 번역도 필요하고요

2024-05-03 16:30 UTC, taggon commented on src/content/reference/react/experimental_useEffectEvent.md
> +Experimental 버전의 리액트는 버그가 발생할 수 있습니다. 제품에는 이 버전을 사용하지 마세요.
- 주술 호응이 안 맞습니다. '리액트에서는 버그가 발생할 수 있습니다'라고 하거나 '리액트에는 버그가 있을 수 있습니다'라고 해야 할 것 같습니다.
- 'in production'은 '프로덕션 환경에서'라는 뜻입니다.

2024-05-03 16:30 UTC, taggon commented on src/content/reference/react/experimental_useEffectEvent.md
> +`useEffectEvent`는 [Effect Event.](/learn/separating-events-from-effects#declaring-an-effect-event) 에 non-reactive 로직을 추출하는 리액트 훅입니다.
다른 번역을 참고해서 non-reactive도 번역해야 합니다.

2024-05-06 12:29 UTC, songjung-good reviewed
오류거 있었네요 감사합니다;)

2024-05-12 04:09 UTC, hg-pyun submitted a review, later dismissed
기여 감사합니다.

2024-05-15 16:35 UTC, gnujoow commented on src/content/reference/react/experimental_useEffectEvent.md
> +
```suggestion
```

불필요한 개행 삭제

2024-05-15 16:35 UTC, gnujoow approved these changes

2024-05-15 16:35 UTC, taggon approved these changes
👍 수고하셨습니다

2024-05-15 16:35 UTC, merged