Translate: form
reactjs/ko.react.dev pull request #909
Opened 2024-05-12 07:22 UTC by deli-ght

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-05-14 02:53 UTC, hg-pyun requested changes

2024-05-14 02:53 UTC, hg-pyun commented on src/content/reference/react-dom/components/form.md
> +리액트의 익스텐션인 `<form>`은 현재 리액트 카나리와 실험적 채널에서만 사용할 수 있습니다. 리액트에서의 안정적인 배포를 위해 `<form>`은 [내장 브라우저 HTML 컴포넌트](https://react.dev/reference/react-dom/components#all-html-components)로서만 동작합니다. 더 자세한 사항은 [리액트
React는 번역하면 안되는 용어에 포함됩니다.

2024-05-14 02:53 UTC, hg-pyun commented on src/content/reference/react-dom/components/form.md
> +리액트의 익스텐션인 `<form>`은 현재 리액트 카나리와 실험적 채널에서만 사용할 수 있습니다. 리액트에서의 안정적인 배포를 위해 `<form>`은 [내장 브라우저 HTML 컴포넌트](https://react.dev/reference/react-dom/components#all-html-components)로서만 동작합니다. 더 자세한 사항은 [리액트
https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary 를 보고 한번 다시 검토 부탁드려요!

2024-05-15 16:32 UTC, gnujoow commented on src/content/reference/react-dom/components/form.md
> -
diff에 보면 line number가 다릅니다. 

추후에 문서가 업데이트 될때 conflict를 야기할 수 있으니 번역본의 line diff가 생기지 않도록 불필요한 개행 혹은 행 삭제는 없도록 수정 부탁드립니다.

2024-05-29 08:50 UTC, hg-pyun commented
@deli-ght 님 코멘트 확인 한번 부탁드립니다!

2024-05-29 09:06 UTC, deli-ght commented
바빠서 확인 못하고 있었네요. 리마인더 감사합니다. 일요일까지 수정해놓겠습니다! @hg-pyun

2024-06-03 13:05 UTC, hg-pyun requested changes

2024-06-03 13:05 UTC, hg-pyun commented on src/content/reference/react-dom/components/form.md
> +리액트의 익스텐션인 `<form>`은 현재 리액트 카나리와 실험적 채널에서만 사용할 수 있습니다. 리액트에서의 안정적인 배포를 위해 `<form>`은 [내장 브라우저 HTML 컴포넌트](https://react.dev/reference/react-dom/components#all-html-components)로서만 동작합니다. 더 자세한 사항은 [리액트
카나리는 Canary(카나리)로 해주시면 좋을 것 같습니다.

2024-06-03 23:19 UTC, deli-ght commented on src/content/reference/react-dom/components/form.md
> +리액트의 익스텐션인 `<form>`은 현재 리액트 카나리와 실험적 채널에서만 사용할 수 있습니다. 리액트에서의 안정적인 배포를 위해 `<form>`은 [내장 브라우저 HTML 컴포넌트](https://react.dev/reference/react-dom/components#all-html-components)로서만 동작합니다. 더 자세한 사항은 [리액트
수정 완료했습니다 :)

2024-06-03 23:19 UTC, deli-ght commented on src/content/reference/react-dom/components/form.md
> -
수정 완료 했습니다! :)

2024-06-10 01:00 UTC, hg-pyun approved these changes
반영 감사합니다 🙇‍♂️

2024-06-10 01:00 UTC, merged