Translate: link
reactjs/ko.react.dev pull request #936
Opened 2024-06-02 13:31 UTC by youngjo-gil

#931 
[link 컴포넌트 페이지](https://ko.react.dev/reference/react-dom/components/link) 번역 완료했습니다.

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-06-03 07:24 UTC, hg-pyun commented
@youngjo-gil 컨플릭트 확인 한 번 부탁드립니다!

2024-06-03 07:29 UTC, youngjo-gil commented
@hg-pyun 컨플릭트 해결했습니다!

2024-06-03 12:59 UTC, hg-pyun requested changes
잘 번역해주셔서 아래 코멘트 말고는 이상 없습니다 👍

2024-06-04 00:03 UTC, youngjo-gil commented
@hg-pyun 말씀해주신대로 반영했습니다! 상세한 리뷰 감사합니다 👍

2024-06-10 01:04 UTC, hg-pyun approved these changes
LGTM

2024-06-10 01:07 UTC, merged