Translate/style
reactjs/ko.react.dev pull request #956
Opened 2024-06-17 18:04 UTC by lydiacho

`<style>` 페이지 번역 완료하였습니다 :) 

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-06-23 06:12 UTC, hg-pyun requested changes

2024-06-23 06:12 UTC, hg-pyun commented on src/content/reference/react-dom/components/style.md
> +React의 `<title>` 확장은 현재 React의 카나리(Canary) 버전 및 실험 채널에서만 사용할 수 있습니다. React의 안정적인 릴리즈에서는 `<title>`이 [내장 브라우저 HTML 컴포넌트](https://react.dev/reference/react-dom/components#all-html-components)로만 작동합니다. 여
여기 링크는 한국어 문서 주소로 해주시면 좋을 것 같아요.

2024-06-23 06:12 UTC, hg-pyun commented on src/content/reference/react-dom/components/style.md
> +[내장된 브라우저 `<style>` 컴포넌트](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style)를 사용하면 문서에 인라인 CSS 스타일시트를 추가할 수 있습니다.
여기도 한국어 번역 페이지가 있다면 거기로 링크하면 더 좋을 것 같습니다.

2024-06-23 06:24 UTC, lydiacho commented
@hg-pyun 국문 문서 링크로 모두 수정하였습니다! 👍

2024-06-26 04:48 UTC, hg-pyun approved these changes
LGTM

2024-06-26 04:48 UTC, merged