Translate: preload
reactjs/ko.react.dev pull request #970
Opened 2024-06-29 11:50 UTC by wet6123

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2024-06-30 06:10 UTC, hg-pyun requested changes
다른 번역문서에서 공통으로 사용하는 용어들 `ex) Returns`을 맞춰주시면 좋을 것 같습니다.

2024-06-30 06:10 UTC, hg-pyun commented on src/content/reference/react-dom/preload.md
> +[리액트 기반 프레임워크](/learn/start-a-new-react-project)는 리소스 로딩을 대신 처리하는 경우가 많으므로 이 API를 직접 호출할 필요가 없을 수도 있습니다. 자세한 내용은 해당 프레임워크의 문서를 참조하세요.
React는 번역하면 안되는 용어에 포함되어있습니다.
```suggestion
[React 기반 프레임워크](/learn/start-a-new-react-project)는 리소스 로딩을 대신 처리하는 경우가 많으므로 이 API를 직접 호출할 필요가 없을 수도 있습니다. 자세한 내용은 해당 프레임워크의 문서를 참조하세요.
```

2024-06-30 06:10 UTC, hg-pyun commented on src/content/reference/react-dom/preload.md
> +#### 반환 {/*returns*/}
```suggestion
#### 반환값 {/*returns*/}
```

2024-06-30 06:28 UTC, wet6123 commented on src/content/reference/react-dom/preload.md
> +[리액트 기반 프레임워크](/learn/start-a-new-react-project)는 리소스 로딩을 대신 처리하는 경우가 많으므로 이 API를 직접 호출할 필요가 없을 수도 있습니다. 자세한 내용은 해당 프레임워크의 문서를 참조하세요.
감사합니다~ 용어집 참조해서 다시 검토 해보겠습니다.

2024-07-01 01:29 UTC, hg-pyun approved these changes
빠른 반영 감사합니다. LGTM 👍

2024-07-01 01:29 UTC, merged